### ISSUE TITLE
Unable to compile an unchanged project

### ISSUE THREAD

**Issue by dgately** [parallaxinc/BlocklyProp#1052]
My first "C" BlocklyProp project for a FLiP board gets an "unable to compile your project" error dialog after a successful compile & upload, without any changes being made between compile attempts.

<img width="898" alt="blocklypropcompileerror" src="https://cloud.githubusercontent.com/assets/3009364/26561376/c43d71a6-4472-11e7-89db-243a11ed243a.png">

After compiling the code, uploading & running it on a FLiP board at least one time, I start getting the above dialog until I do a SHIFT-ALT-R on my Mac. Then the code compiles, uploads & runs just once more. The cycle of compile then not compiling starts again... The BlocklyProp code is in my projects as "FLiPTest 1" (dgately@me.com)

Here's the BlocklyProp code:
<img width="726" alt="flipcode" src="https://cloud.githubusercontent.com/assets/3009364/26562117/74fb2b50-4478-11e7-91f6-66f844d43cac.png">

Interestingly, the project produces this "C" code from Blockly and it builds & runs over and over again.

`// ------ Libraries and Definitions ------
#include "simpletools.h"

// ------ Function Declarations ------
void TEST1();
void TEST2();

// ------ Main Program ------
int main()
{

    // FIRST TEST
    pwm_start(100);
    cog_run(TEST1, 128);
    cog_run(TEST2, 128);
    while (1)
    {}

}

// ------ Functions ------
void TEST1()
{
    pwm_set(26, 0, 10);
    while (1)
    {}
}

void TEST2()
{
    pwm_set(27, 1, 100);
    while (1)
    {}
}`

**Comment by MatzElectronics** [comment]
@PropGit any ideas here?

Here's what I've noticed - if you leave the Propeller in s state with a tight loop (an empty while(1) for example), it has a REALLY hard time letting itself be reprogrammed.  I have experienced this on several occasions.  @dgately my advice here is to, at a minimum, include a pause inside of the main loop's repeat forever block.  It my also work without the repeat forever block at the end at all.

**Comment by PropGit** [comment]
@MatzElectronics I think we're talking about two different things here.

The error message says "[object Object]" indicating to me that a JavaScript object variable has been left uninitialized.  I can't explain why that's happening every other time though.  I have not tried this code myself, but will do so next.

The really tight loop issue is baffling too.  Regardless of activity on the Propeller, the host system resets it (halting it in it's tracks) at that start of programming.  If you're unable to program it again, I'd think it's because a tight loop was outputting lots of serial data and that data perhaps hasn't been properly flushed from the host's receive buffer after it resets the Propeller (a problem with the loader).

I'll explore that as well.

@dgately - can you confirm that even just compiling (not compiling+download-to-RAM causes the same error you are having?

**Comment by PropGit** [comment]
@MatzElectronics @zfi - I believe I have the answer.  What @dgately is experiencing is our system's compilation-throttling protection.  We designed it to provide each session with a certain number of "compilation rights"... they can be used up faster than they are re-granted so that sessions that are compiling over and over in short-order are eventually held back to allow cloud compiler resources to be available to other sessions.  

In my tests, I was able to compile over and over again successfully until I eventually exhausted a certain number of tries... then it failed to compile _each and every_ time I tried (not every other time) until I slowed down, bided my time, and then tried again.  Waiting even longer between successive compiles allowed me to compile two or three or four times in a row, in quick succession, before I suddenly was met with the error again.

Refreshing my browser without cache had no true effect on this... as designed; however, if those refreshes were also associated with enough time-passed, it'd appear that they caused it to compile successfully again.

I've run into this issue a few times myself in the past, often when I'm trying to test the heartiness of our updated loaders.

Maybe we should relax the restrictions a little bit to allot a few more compilation rights (tokens) to each session.  Not sure if we should just change the fill rate.

At the very least, we should look into catching this event and providing a better message to the user, perhaps "Cloud compiler service is busy; please try again later." instead of the general message we have now which doesn't really lead the innocent user to doing the correct action.

**Comment by MatzElectronics** [comment]
Lets try to trap that [Object object] thing into a console.log, that way we can actually see what's inside it so that perhaps we can parse it a bit better...

**Comment by zfi** [comment]
In blocklyc.js at around line 220, there is a call to a rest endpoint that **may** return data if the endpoint did not throw an exception. If the pool of compile tokens has been depleted, the endpoint would throw an ServerException and return a null. The if statement that is evaluating the error element should verify that the variable is not null first.

```
        <...>
            'url': baseUrl + 'rest/compile/c/' + action + '?id=' + idProject,
            'data': {"code": propcCode}
        }).done(function (data) {
            if (data.error) {       // <========== possible null
                console.log(data);
                if (typeof data['message'] === "string")
        <...>
```

**Comment by MatzElectronics** [comment]
This has been corrected in the last round of compile message fixes.
