### ISSUE TITLE
Spaces in a variable stop code from compiling

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#1062]
When putting a space in a blockly variable, the code correctly labels the variable as 

```C
int Key_Number
```

However when the variable is used in the program, there is always a "2" added to the end of it.

```C
// ------ Libraries and Definitions ------
#include "simpletools.h"

// ------ Global Variables and Objects ------
int KeyNumber;
int Key_Number;



// ------ Main Program ------
int main()
{

    KeyNumber = 1;
    Key_Number2 = 0;

}
```

This code just sets the variables "KeyNumber" and "Key Number" equal to 1 and 0, respectively, to show the difference.

This is only an issue with variables, not functions. Here is a link to a project where variables have spaces: http://learn.parallax.com/tutorials/language/blocklyprop/rfid-scan-and-store-eeprom-project/test-out-full-program

**Comment by MatzElectronics** [comment]
It took me a while to figure this out, but here's what is happening:
a while back we added some code/regex to filter out unwanted/illegal user input for variable and array names.  It turns out that the Blockly core already had some of the protection built in, so when we added what we did, the core is seeing it as a duplicate variable, and adding a 2 to it.
I simply need to completely test the behavior of the offending code, and either modify or remove it depending on the results of that testing.

We also, for the sake of consistency and training students to create proper variable names, change published examples that have variable names with spaces.

I'll submit identical fixes to demo and 0.97

**Comment by kgracey** [comment]
Your last statement - please confirm that we should change our posted examples to exclude spaces in variable and function names - is this correct?

**Comment by MatzElectronics** [comment]
Gradually, yes.  I'd like to get it back to where they are supported so
that'll doesn't break, but as a matter to teaching students to "do it
right", we should be a good example :)

**Comment by kgracey** [comment]
OK, I’ve got an intern to help out so I’ll get @carsongracey to give me a hand. We can do this - no problem. KG

**Comment by zfi** [comment]
This issue has been corrected with the a patch to the blockly/generators/propc/variables.js file. The patch is live in all sites (Coppa, Demo and Beta).
