### ISSUE TITLE
Obstacle detection sensors have poor detection

### ISSUE THREAD

**Issue by dcarrier-parallax** [parallaxinc/BlocklyProp#1158]
The obstacle detection blocks in Blockly do not reliably detect obstacles, but the S3 GUI produces code that works well.  See the example Blockly program at http://demo.blockly.parallax.com/blockly/my/projects.jsp#262 and this S3 GUI program: [Obstacle.zip](https://github.com/parallaxinc/BlocklyProp/files/1229831/Obstacle.zip)

I have tested this on S2 and S3 robots, with the same results.

**Comment by MatzElectronics** [comment]
@dcarrier-parallax Could I ask a big favor? If you are able, could you send me the SPIN generated by the example?  I don't have the S2/S3 GUI installed...

**Comment by CGracey** [comment]
I tested four S3's and the obstacle detection blocks all seemed to work. Every S3 had a detection range that was roughly a foot while one only detected up to 4 inches (left, right, and center). There doesn't appear to be any major problems from what I can tell.

**Comment by MatzElectronics** [comment]
Same here, I can get it to work well enough on s3's as well - I want to leave this open because I'm sure it can be improved.  Perhaps some instructions would be helpful...for example, include a short (100 ms) pause in the loop if there are no other actions or commands and test for the center position (least likely) condition first before elseif-ing the other conditions.

**Comment by kgracey** [comment]
@dcarrier-parallax please test with some 100 ms pauses as @MatzElectronics suggested and report back.

**Comment by MatzElectronics** [comment]
This was fixed, tested, and verified - SimpleLibraries issue.
