### ISSUE TITLE
Arlo Blocks in Robot Category

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#1229]
![arlo](https://user-images.githubusercontent.com/8891440/31572950-e389d62e-b076-11e7-859f-84b7388169ac.JPG)

@MatzElectronics - Note the following in regards to the Arlo Blocks in the Robot category of BlocklyProp.

- On the Robot "Arlo" initialize block - can we remove the warning and add it instead to the blocks we still have issues with?

- Robot set acceleration - Not Working.

- Robot drive speed - Seems to work correctly - can you clarify the limits? -128 to 128 - is that correct - I know that this is the range allowed, but is this correct for Arlo?

- Robot drive distance - Seems to work correctly - can you clarify? A full wheel rotation is 372 ticks, correct? Is their a distance calculated (I can do this empirically) on how far a single wheel turn should travel?

- Robot set max speed - Not Working

- Robot drive stop - same as Robot drive speed or drive distance - left 0 and right 0?

**Comment by MatzElectronics** [comment]
- Yes, we can remove the warning
- Got it
- I think the Arlo will actually take a wider range +/- 200, but does the block throw a warning outside of +/- 128?  I don't recall ??  Range and block behavior needs to be tested
- I'll have to look at the ratio I used in the block and get back to you...  I know I measured and tested this...
- Got it
- Yes, sets speed to 0,0

**Comment by wstodghill** [comment]
Yes - Speed gives a warning outside +/- 128. See below...
![speed](https://user-images.githubusercontent.com/8891440/31583879-7f3baf92-b168-11e7-897a-572230c9eda1.JPG)

**Comment by wstodghill** [comment]
@MatzElectronics, @kgracey 

I know that this is **low** on the priority list, but any progress on these blocks? If I understood how this works more, I would be glad to help.

Are there any experiments I could do to help?

**Comment by MatzElectronics** [comment]
Hi!  The next PR will address a couple of things in this thread - I'll move the arlo warning to the two blocks that aren't working instead of the init block, and I'll change the range warning on the speed block to +/- 500.

To address an earlier question you had - I'm hesitant to change the units, or round them to nice numbers like 100 or 360 - because if they aren't accurate, errors will accumulate pretty quickly - they already do with the little bit of rounding that's already there.

**Comment by wstodghill** [comment]
@MatzElectronics - Thanks! - I will give it a check! May have a bit of time tomorrow.

**Comment by wstodghill** [comment]
@MatzElectronics - Works as advertised in Demo (in Louisiana).

**Comment by MatzElectronics** [comment]
Thanks!  I'm going to pull the requires verification and In Demo labels and add a c library dependency because ultimately, this still needs to get fixed :)

**Comment by wstodghill** [comment]
@MatzElectronics - Anything I can test to help get the ball rolling?

**Comment by wstodghill** [comment]
Any progress or thought about the rest of the Arlo blocks in BlocklyProp?

As of June 6, 2018 - these are the current Arlo Robot blocks for the Propeller Activity Board WX.

![arlo blocks](https://user-images.githubusercontent.com/8891440/41062372-4059e82a-699b-11e8-8fc2-beb38adce2e8.JPG)

**Comment by MatzElectronics** [comment]
As always, we'd like to see them all working, but unfortunately no official
timeline for additional support beyond what is there, simply because we
have a few too many other projects in the pipeline :)

That being said - we are always open to help from the community.

If you can make it work in C, I can easily make BlocklyProp do it.  What
probably needs to happen, however, is for libarlodrive.h to be added to so
that it has the functionality that is being warned about in those blocks.

Keep me posted, and I'm happy to help if you dive into it.
-Matt

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>  |  Licenses
<http://www.tspc.oregon.gov/lookup_application/LDisplay_Individual.asp?id=07080L3B270>

**Comment by wstodghill** [comment]
@MatzElectronics 

Okay. I will keep playing - I think I can make it work is C (but may looks for some tricks in Blockly!)

Thanks for the help and encouragement. I always end up learning something by trying to do things. Keep working on all our other fun new features!

**Comment by MatzElectronics** [comment]
@wstodghill Something to consider would be trying to command the Arlo via serial comms using the command set for the DHB10...part of the issue is that the arlodrive library is that it's only calling very basic drive functions, and layering stuff on top of them, instead of letting the DHB10 handle all of this stuff. As a result, the DHB10's drive commands are being called too frequently, and that's making it buggy.  @dcarrier-parallax may have some more to contribute here as well.

**Comment by wstodghill** [comment]
@MatzElectronics - Thanks, will give that a try! Happy Thanksgiving!

**Comment by wstodghill** [comment]
We should close this - till I can return and wrestle with it some more.
