### ISSUE TITLE
Redundant message handlers

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1349]
@MatzElectronics 

There are currently redundant connection.onmessage handlers with different code in each, right next to each other.

https://github.com/parallaxinc/BlocklyProp/blob/dfbadc3744e5f4b605f57bc5d673f7f43c4ae7f3/src/main/webapp/cdn/blocklyc.js#L655

![image](https://user-images.githubusercontent.com/1266318/34899976-19227b20-f7b1-11e7-9a40-47d4a60f7662.png)

**Comment by MatzElectronics** [comment]
Fixed.

On Jan 12, 2018 3:56 PM, "Parallax Git Administrator" <
notifications@github.com> wrote:

Assigned #1349 <https://github.com/parallaxinc/BlocklyProp/issues/1349> to
@MatzElectronics <https://github.com/matzelectronics>.

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/parallaxinc/BlocklyProp/issues/1349#event-1422728035>,
or mute the thread
