### ISSUE TITLE
Project "share link" - should it be a fixed value in the DB, or auto-generated?

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#1406]
Point of discussion related to the share-link.

From @zfi:
My notes from this indicate that we should create the shared link at the time the project is created. The checkbox for sharing the link becomes an enable/disable toggle. The shared link should allow an anonymous user to view the project but not edit it. A logged in user can view it, edit it and save it. The save operation in this case is what we currently call a 'clone project' operation.

This involves endpoints and possibly an additional DB record...

**Comment by zfi** [comment]
Following up on this change: 

The 'shared' field in the project table currently indicates if a sharable link exists for the project. It also implies that the link is active if it exists. Going forward, if 'shared' is non-zero, it means that there is a matching record in the project_shared table that hold the GUID used to create a project sharing link.  Otherwise, it indicates that there is not a shared project link record for the current project.

Add a Boolean 'active' field in the project_shared table to indicate the state of the link. True, the link is active; False means the link is inactive. In the inactive state, any request for the project made via the shared project link will fail with a 404 - Page not found error. 

The 'shared project' checkbox in the UI will have a new behavior after this set of changes. Starting with a new project, the checkbox is initially unchecked. When the box is checked, the system will attempt to locate the matching project_shared record. If unsuccessful, the system will create the project_shared record and set the 'active' field to True.

When the 'shared project' checkbox is unchecked, the behavior is changed to no longer remove the related project_shared record but, instead, simply marks the 'active' field in the existing record to False. The next time the box is checked, the system will locate the already existing project_shared record and set the 'active' field to True.

When the project record is deleted, the related shared_project record is also removed. 

This behavior works well for the existing records in that the records that already exist are all actively shared. The update the deploys this set of changes will set 'active' field on all existing shared project to active.

The project_sharing table contains fields to support link expiration. I don't see that this feature is expressed in the code but we might want to enable it such that the link is active until a specified date. The link then goes inactive but is never actually removed until the parent project is deleted.

**Comment by MatzElectronics** [comment]
Tested, validated, included in 0.100
