### ISSUE TITLE
BADGE:  can't print a number to the screen (issue with var types)

### ISSUE THREAD

**Issue by cbradyatinquire** [parallaxinc/BlocklyProp#146]
Right now, the "print a variable" block under OLED, has the following problem.

1) its variable socket ACCEPTS a numeric value (e.g., get accelerometer reading)
2) it does not compile with such a value in the socket
3) there is no way to convert from number to string.

The suggested remedies for this are.  
a) make the socket data-type sensitive (I believe Blockly allows this) - introduce a color scheme for variable types, to visually distinguish string from numeric.
AND
b) create a block that converts a number to a string.

OR
c) make the socket DO the conversion to string for any block that it accepts.  This is (IMHO) the best solution for the user audience (though it might not be easy to achieve).

**Comment by DarkmatterVale** [comment]
I think option c is the preferred route to go. This makes it easy on the user and does not require additional blocks to be created (which could further confuse the user). I do not think it is that difficult to achieve since there are functions available in C to convert other data types to strings.

While I am working on this block, I think it would be a great idea to have it have a default value block. I suggest we do something like:

![screen shot 2016-03-10 at 7 19 28 am](https://cloud.githubusercontent.com/assets/6094957/13669387/258aa0aa-e691-11e5-9f89-4f79b4418453.png)

Thoughts?

**Comment by DarkmatterVale** [comment]
I also think we should change the name of the block to just "Print". Although it will be the same as the other print block, it will accept a different value type which will differentiate them.

**Comment by DarkmatterVale** [comment]
bump

**Comment by PropGit** [comment]
@DarkmatterVale 
> I also think we should change the name of the block to just "Print".

Is there a way for a single Print block to accept multiple value types?  That'd be best, rather than two blocks of exactly the same name the require different types; otherwise, I think they'd be indistinguishable and that'd be confusing.

**Comment by DarkmatterVale** [comment]
@PropGit Yes, we can have it accept multiple value inputs. However, we are not able to allow 2 types (its all or one I believe). @michel-cf Can you confirm that ```.setCheck(---)``` can only be applied once to a block?
