### ISSUE TITLE
Badge WX Unlock/Lock Block Request

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#1521]
The 6x button-press can be difficult to do in a timely manner, and confusing for some users. Please add these blocks. For detail, I've copied a message that explains the issue:

Use the BadgeWX LOAD menu feature, and upload some Blockly code (run or eeprom, don't matter). 
The code will run immediately, so the Badge menu will have exited and yes, Badge will have re-locked. 
So whilst your user code is running, you can't just upload another version of your Blockly code. 
Not unless your Blockly code has set P17 high when it runs, to keep the badge unlocked and open to continuous updates.

<snip>
(Hmm... maybe that's a block to add? LOCK / UNLOCK BADGE.... which would set P17 high to unlock, back to input to lock).

(And there's another block idea for the Advanced WX blocks for BadgeWX.... WX module RESET... which would toggle P16; low for >100uS, then back to input)

6 Presses...

This overrides whatever the Propeller lock control is doing on P17 (via the Badge menu system or user code). It forces the WiFi module to remain unlocked until the next powercycle. 
So if you connect to a WiFi network, press pwr 6 times (instead or as-well-as clicking the BadgeWX LOAD menu option), now the badge is unlocked through user code uploads. 
You can keep uploading revisions of Blockly code as many as you like until the next powercycle.
<snip>

Thanks!

**Comment by PropGit** [comment]
Thoughts: The UNLOCK/LOCK BADGE block idea is a good one for even other purposes than this, so I think that's a good idea, but I still think it too awkward to make it a standard practice for normal badge development.  For one thing, people will inevitably leave it in their code and their badge will _always_ be unlocked without them realizing it.

I have a suggestions:
1. [Badge Firmware Enhancement] Currently, the LOAD menu item, when pressed, activates a one-time unlock (programming) feature and displays 
~~~
WiFi Programming
   Activated!

  <badge name>

           ABORT"
~~~
Instead, let's make the press of the LOAD menu item permanently unlock the badge by default (until power-cycle) and display
~~~
Unlocked!     
----------------
WiFi Programming
   Activated!

  <badge name>

ONCE       ABORT"
~~~

Then the user can press the left navigation button _only_ if they want it to be a one-time unlock, otherwise, it's unlocked until the next power-cycle.  Upon the first download while this menu is displayed, we'll make the micro-boot loader clear the OLED screen (ie: menu goes away; which solves another source of confusion if their newly downloaded code doesn't exercise the OLED).

2. [Badge Power Button Firmware Enhancement]  Maybe we can make the 6-press sequence a little easier by increasing the allowed-delay between button presses... the user won't have to press it as swiftly to activate the permanent unlock feature.

**Comment by MatzElectronics** [comment]
So...what color, what menu, what block text?

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>  |  Licenses
<http://www.tspc.oregon.gov/lookup_application/LDisplay_Individual.asp?id=07080L3B270>

**Comment by Steph-Parallax** [comment]
@MatzElectronics  I'd like to see this block as its own subcategory under Communication if no one else objects.  All items in the Control menu work with all board types. Yes it will have its own Help page but it will need considerable explanation anyway.

**Comment by Steph-Parallax** [comment]
@MatzElectronics Help URL: ....ab-blocks/badge-lock

**Comment by kgracey** [comment]
Works as advertised perfectly. Keep the LOCK and UNLOCK, scrap the third option "LOCK AFTER WX RESET" as this is not needed yet, until advanced users start needing it.
