### ISSUE TITLE
Add System Blocks to Propeller Activity Board type

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#1546]
Reason is here https://learn.parallax.com/tutorials/language/blocklyprop/visual-metronome-project/metronome-assembly-and-code-overview - ease of using it as a standard feature is now important. @dcarrier-parallax suggested an improvement to the Wait Until block as well, tagged here so he replies or creates a separate issue.

**Comment by PropGit** [comment]
Why not make the System Blocks available to all project types, except possibly Scribbler Robot if you're wanting to keep it simple.

Also for consideration- the **Wait until** block is a control feature and, especially as currently written, should be in the Control category right next to the **pause (ms)** block.

**Comment by kgracey** [comment]
Your solution is also preferable @PropGit. Where they go? No input on that. The best place?

**Comment by MatzElectronics** [comment]
Made some progress on this, but I'd like to know what @dcarrier-parallax has for a suggestion before I go much further.

My $0.02 on this - the "system" category is a place for advanced use blocks, so while the wait until block might fit programmatically in control, it's conceptually in a more advanced class...

**Comment by Steph-Parallax** [comment]
System should be an option in all block types except S3 now;  keeping Wait until with System due to its complexity of use and prior tutorial dependencies.

**Comment by zfi** [comment]
@wstodghill : The Demo server is our designated blast zone for new code. Out internal build systems  automatically notice the code changes, build new applications and install the on the Demo server. Once we're pretty happy with the stability of the updates in Demo, we prepare a release cycle for the production system. Those updates are a little more complex because the production system is actually a half dozen servers all handling specific services.

All this really means is that you will usually see things working on the Demo server before they show up on the production systems. And, in some cases, broken things we find in production will usually be corrected on the Demo service first. Unless it's significantly impacting the user experience. Then we will patch on both systems simultaneously.

Happy Friday!

**Comment by wstodghill** [comment]
@Steph-Parallax - Verified in DEMO.

**Comment by MatzElectronics** [comment]
Perfect, thanks!
