### ISSUE TITLE
add "remainder" to reserved word list

### ISSUE THREAD

**Issue by Steph-Parallax** [parallaxinc/BlocklyProp#1549]
Using "remainder" as a variable throws an error, described with screencaps here:

[https://github.com/parallaxinc/Simple-Libraries/issues/176#issuecomment-422596117](url)

**Comment by PropGit** [comment]
We need to add "remainder" to BlocklyProp's list of reserved words, per [this conversation in Simple Libraries](https://github.com/parallaxinc/Simple-Libraries/issues/176#issue-361512063).

**Comment by wstodghill** [comment]
@Steph-Parallax 

This code in Blockly (Board set for FLiP)

![test remainder is reserved word blocks](https://user-images.githubusercontent.com/8891440/46848842-bf77b900-cdb1-11e8-9583-f63b54d89a4b.JPG)

produces this in C

![test remainder is reserved word - generated c](https://user-images.githubusercontent.com/8891440/46848857-db7b5a80-cdb1-11e8-9152-21960250bab6.JPG)

Since it my named variable remainder is listed remainder2 in the code, does that mean that "remainder" is already assigned and has been reserved? If so, looks like this works.

**Comment by MatzElectronics** [comment]
Yup, that is the intended effect.
Thanks @wstodghill !
