### ISSUE TITLE
User defined code block Help goes to wrong URL

### ISSUE THREAD

**Issue by Steph-Parallax** [parallaxinc/BlocklyProp#1558]
@MatzElectronics  User Defined Code block should appear under System menu where it is available for a board type, and its URL should go to ab-blocks/system.

**Comment by VonSzarvas** [comment]
Don't know if your moving the user block out of badgewx, but Corey needs it this weekend for Maker Faire.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Steph-Parallax <notifications@github.com> Date: 02/10/2018  22:55  (GMT+01:00) To: parallaxinc/BlocklyProp <BlocklyProp@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [parallaxinc/BlocklyProp] User defined code block Help goes to wrong
  URL (#1558) 
@MatzElectronics  User Defined Code block should appear under System menu where it is available for a board type, and its URL should go to ab-blocks/system.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/parallaxinc/BlocklyProp","title":"parallaxinc/BlocklyProp","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/parallaxinc/BlocklyProp"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"User defined code block Help goes to wrong URL (#1558)"}],"action":{"name":"View Issue","url":"https://github.com/parallaxinc/BlocklyProp/issues/1558"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/parallaxinc/BlocklyProp/issues/1558",
"url": "https://github.com/parallaxinc/BlocklyProp/issues/1558",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "User defined code block Help goes to wrong URL (#1558)",
"sections": [
{
"text": "",
"activityTitle": "**Steph-Parallax**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Steph-Parallax",
"facts": [
{
"name": "Repository: ",
"value": "parallaxinc/BlocklyProp"
},
{
"name": "Issue #: ",
"value": 1558
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"parallaxinc/BlocklyProp\",\n\"issueId\": 1558,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"parallaxinc/BlocklyProp\",\n\"issueId\": 1558\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/parallaxinc/BlocklyProp/issues/1558"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 387147840\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Steph-Parallax** [comment]
It is currently available for everything but S3 and will stay that way!

**Comment by wstodghill** [comment]
@Steph-Parallax - Works for all board types (except S3) on the DEMO BlocklyProp site - Help right click on User Defined Block goes to Propeller BlocklyProp Block Reference and the System>
BlocklyProp reference for SYSTEM blocks.

On the Live BlocklyProp site - Help right click on the User Defined Block still incorrectly links to Propeller BlocklyProp Block Reference and the Control > BlocklyProp reference for CONTROL blocks.

FIX works as it should on DEMO and the Live Site should be fine once updated.

**Comment by wstodghill** [comment]
@Steph-Parallax - Works on DEMO - see above - Still linked incorrectly on Live Blockly. If we are just checking the DEMO - We've got this one!

**Comment by MatzElectronics** [comment]
Yup, just demo, will propagate up when we do the next upgrade.  Closing.
