### ISSUE TITLE
List pages skip projects at 100 per page

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#1645]
Setting the list page to 100 records per page causes projects to be skipped in-between pages.

When set to view 100 records per page, but it really only shows the user the first 50 rows... but the next page (ie: between pages 1 and 2) skips 50 rows and displays what appears to be rows 100 - 149.  Every other group of 50 is skipped.

**Comment by zfi** [comment]
This is caused by a somewhat arbitrary limitation that was placed in the server code to prevent a session from listing ALL of the projects. The relevant source was hard-coded a limit of 50 rows of data per call. This has been refactored to a hard limit of 100 items. A TODO has also been added to make this an application configuration setting.

**Comment by PropGit** [comment]
Thanks @zfi.
