### ISSUE TITLE
SaveAs causes BlocklyPropClient connect to be lost

### ISSUE THREAD

**Issue by VonSzarvas** [parallaxinc/BlocklyProp#1696]
From Blockly page, use the top-right dropdown menu to "SaveAs" a new project name.

Immediately the Client connection is lost. Message appears top left, " Looking for BlocklyProp-Client..."

Refresh usually solves, but not always.

Guess- the SaveAs command might need to "disconnect" from the BlocklyClient connection, so that a new "connection" can occur in the background, with the new file.

**Comment by PropGit** [comment]
Please report what browser and version of browser you are using.

I think this relates to Issue #1687.  Also, people have recently experienced lack of reconnection when they go to switch projects and come back to the editor.  I've noticed it happening a lot more frequently now since Chrome 74+ was released - I theorize that there's been an order-of-events issue for a while and now Chrome's Javascript engine is improved (running faster) and probably is affecting the order in which certain events fire.

**Comment by VonSzarvas** [comment]
Chrome 75 on Windows 10

#1687 looks in the same ballpark. Oh joy !

**Comment by PropGit** [comment]
@VonSzarvas - I think the issue has been patched in Demo.  Can you retest in demo to verify?

That fix will have to be deployed to Production soon because it's definitely becoming more frequent and affecting multiple people.

**Comment by PropGit** [comment]
@VonSzarvas - I've now patched Production as well.  Please retest and report whether you experience the problem again or not.

**Comment by PropGit** [comment]
Notes: Hot patched blocklypropclient.js to be that of the current tip of development:  https://github.com/parallaxinc/BlocklyProp-cdn/commit/af74bfd6aa81cb7930259fb84ca08d22343e19e2

**Comment by VonSzarvas** [comment]
> @VonSzarvas - I've now patched Production as well. Please retest and report whether you experience the problem again or not.

Production tried a few time today.... SaveAs issue resolved.
* Thank you *

**Comment by PropGit** [comment]
That's great news.  Thank you for confirming.
