### ISSUE TITLE
Set pins block does not work

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#189]
The block's UI does not work nor does the block generate the correct code.

To reproduce this error, simply place the block anywhere in your program and select one of the dropdowns. Attempt to change any of the settings and it will not work.

**Comment by michel-cf** [comment]
Fixed using a Blockly modification: retest needed if that gets upgraded:

Blockly.RTL?Blockly.FieldDropdown.ARROW_CHAR + " ":" " + Blockly.FieldDropdown.ARROW_CHAR))
instead of:
a.RTL?Blockly.FieldDropdown.ARROW_CHAR + " ":" " + Blockly.FieldDropdown.ARROW_CHAR))

(a is compressed representation of 'block')
