### ISSUE TITLE
Put Block definitions in shared code between spin and c

### ISSUE THREAD

**Issue by michel-cf** [parallaxinc/BlocklyProp#199]
@DarkmatterVale @PropGit 
Would it be a good idea to put the Block definitions (how they look and behave on screen) in shared files, with only language specific code generators?

This would improve consistency between the 2 languages.
Maybe this is not possible for all blocks, but I would think it should work for most of them.

**Comment by DarkmatterVale** [comment]
Since this will not affect the user's experience with BlocklyProp, I think that we should leave the system the way it is right now. We need to focus on getting a feature-complete system ready as soon as possible, and I can work in separate directories without any issues. After we have the features needed integrated, we can go back and do more behind-the-scenes work which will make it easier to write blocks in the future.

**Comment by zfi** [comment]
There are redundant code blocks between spin and c that may come back to bite us if they do not remain synchronized. Let's queue it for refactoring after we push through a release.

**Comment by DarkmatterVale** [comment]
Since spin will eventually be removed, I am going to close this issue.

**Comment by dcarrier-parallax** [comment]
For S3 support, spin will not be removed, so this issue is now open again.

**Comment by DarkmatterVale** [comment]
Yes, this should be reopened, but I will need time before I can address it

**Comment by MatzElectronics** [comment]
We are actively transitioning to an all PropC system - closing.
