### ISSUE TITLE
Bluetooth port on the Mac: can these be re-ordered?

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#227]
From my e-mail to Michel:

Hello, 

On the Mac (and maybe other platforms) the first port available to be chosen is “Bluetooth”. Considering we don’t have Bluetooth programming support I’d like to limit the programming ports to USB-only connected hardware. Is there a problem doing this, or is this list of port possibilities automatically generated from something behind the in some “port availability” kind of tool?

Michel, could you omit Bluetooth ports as an option for now?

Thanks!

**Comment by michel-cf** [comment]
I'll include this in the new BlocklyPropClient. As we possibly want different functionality in port ordering and filtering based on the OS, the only point to do this is in the Python code of the BlocklyPropClient.

As I'm in the progress of rewriting this, I don't see any advantage in putting more work in the old one.

**Comment by PropGit** [comment]
@michel-cf - We'd like to bump this up in priority; it will be a frequent nuisance to many people soon.

**Comment by PropGit** [comment]
For our legacy Windows software, we automatically exclude any ports with a description matching "*Bluetooth*" and "* BT *" as those are the common pattern among Bluetooth ports on those systems.

A similar technique could be used here, where BlocklyPropClient simply prefilters the list based on textual rules before it delivers the list to the BlocklyProp Editor.  I think this would be a relatively quick fix to apply instead of waiting to rewrite BlocklyPropClient.

The net shows the following possibilities:
> /dev/tty.Bluetooth-Modem
> /dev/tty.Bluetooth-PDA-Sync 
> /dev/cu.Bluetooth-Modem
> /dev/cu.Bluetooth-PDA-Sync

@kgracey - can you check your system and tell us the exact port name?  Does it match one of the above?

**Comment by michel-cf** [comment]
Builds provided to Parallax for testing and signing.

**Comment by PropGit** [comment]
@michel-cf 
- The Win 64-bit version is tested and signed.  Unable to test for filtered Bluetooth, but I expect it is fine.
- The Win 32-bit version installs but fails to run because of missing mscv100? file.
- The Mac 64-bit version runs and filters Bluetooth ports perfectly, but reports the wrong version number in its About page.

**Comment by PropGit** [comment]
- The Win 64-bit version will be deployed soon.
- The updated Mac 64-bit version was received with updated About page.  It will be deployed soon.
- Will wait for an updated Win 32-bit version.

**Comment by PropGit** [comment]
__[UPDATE]__
- I built the Win 32-bit version.  It will be on Demo and Production soon.
