### ISSUE TITLE
Correction to the Sony Remote block code

### ISSUE THREAD

**Issue by Wierdowl** [parallaxinc/BlocklyProp#274]
When I created These blocks:
![screen shot 2016-06-27 at 10 47 17 am](https://cloud.githubusercontent.com/assets/20117212/16389640/aeefca2e-3c53-11e6-91cb-ed3419a747f8.png)

I got this C code:
```

#include "simpletools.h"
#include "sirc.h"

int remote;

int main() {
  sirc_setTimeout( 70 );

  remote =  s;

}

```

And when I went into Simple IDE I was able to change it to this:

```
#include "simpletools.h"
#include "sirc.h"

int remote;

int main() {
  sirc_setTimeout( 70 );

  remote = sirc_button(10);

}
```

Where I changed the "remote = s;" into "remote = sirc_button(10)"  And it was able to work. -Blake

**Comment by DarkmatterVale** [comment]
Gosh dang it I hate this bug so much...I will have this fix included in the next PR

**Comment by kgracey** [comment]
Thankfully you are already familiar with the bug, so the hunt is already over before it began.

**Comment by DarkmatterVale** [comment]
Can someone please verify?

**Comment by CarsonGracey** [comment]
Tested and Verified.

**Comment by DarkmatterVale** [comment]
I believe this has been merged into master, because I see the code is correct. However, when I go to the official BlocklyProp site, I do not see the change in place (this could be because automatic builds of the main branch have not begun yet I believe).

If this issue persists on the main branch, please create a new issue or re open because I believe this has been fixed.
