### ISSUE TITLE
Rename Communicate / Serial Terminal to Communicate / Print

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#329]
It would be more intuitive to rename the Serial Terminal to Print.

**Comment by kgracey** [comment]
Tested and verified with one small change: Print should be print (lower case).

**Comment by DarkmatterVale** [comment]
Ahhhhhhh ok

**Comment by DarkmatterVale** [comment]
Just pushed this update to Demo

**Comment by CarsonGracey** [comment]
One small thing, I think he wanted Print in the menu to be upper case while this print block:
![print](https://cloud.githubusercontent.com/assets/20099916/16810877/aa2b7f9a-48da-11e6-9f73-16b83089ed2e.PNG)
could be all lowercase.

**Comment by kgracey** [comment]
The "print" menu on the left side should be capitalized as in "Print".

**Comment by DarkmatterVale** [comment]
Just pushed a new commit to demo to fix my changes

**Comment by CarsonGracey** [comment]
We get closer every time, but now the top print block is capitalized.

![print fix](https://cloud.githubusercontent.com/assets/20099916/16926996/2aaa4b48-4ce0-11e6-8964-5bdb36217ca5.PNG)

**Comment by DarkmatterVale** [comment]
I'm not sure why this is happening because it is correct on my dev setup. I suspect this is one of the first issues that we see with the Demo system "diverging" from the development setups. This is caused by all of the required rebasing and changes locally. I unfortunately do not know how to fix this because it works fine on my end.
