### ISSUE TITLE
Old projects need to be removed

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#345]
I got an error on my dev VM which I couldn't figure out until I realized that I've made significant changes to blocks in the past few days which broke backwards compatibility. Someone needs to go through all of the old projects that are broken and either:

1) fix them
2) delete them

**Comment by PropGit** [comment]
I went through the App account on Demo and deleted or corrected a bunch of projects that I had created.  Since then, I'm pretty sure more have been broken due to more changes similar in nature to what @DarkmatterVale reported.

Not sure it's a big worry for Demo, unless those are all public projects.

**Comment by MatzElectronics** [comment]
More on this in #843.  Closing this to move the discussion/progress to that issue.
