### ISSUE TITLE
Change Spin titles to Scribbler

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#357]

**Comment by michel-cf** [comment]
Why???

**Comment by PropGit** [comment]
I too wonder what the reason is here.  Scribbler is not the language, it's hardware whose routines are implemented in the Spin language.  If we are changing every occurrence of "Spin" in BlocklyProp to be "Scribbler" it's the same as changing every occurrence of "C" in BlocklyProp to be "Activity Board WX" or "Hacker Electronic Badge."

**Comment by kgracey** [comment]
Correct @PropGit. The question, really, is "how do we simplify and streamline the interface considering the S3 is the only hardware device we will support for Spin?" This entire issue is a matter of user interface design. It would be best if users didn't have to see the Spin choices and everything looked like C unless they chose the S3. How could we accomplish this? At present, there are many opportunities for making a wrong turn when using Blockly, and having some resultant confusion when Spin code shows up. 

What if we approached this issue from a hardware perspective instead of a language? In other words, choose the PAB, Badge and the code is C; choose the S3 and the code is Spin? Would this kind of redesign work?

**Comment by PropGit** [comment]
I'm interested is what ideas @michel-cf may have for this.  I understand your point, and I don't like the awkward steps to get a project going either (including the distinct step to select language); I just caution that we might be painting ourselves into a corner that may be hard to get out of later. 

For example, suppose in the near future after many people have been using BlocklyProp (lots of projects exist), we are encouraged by educators to heartily support C++ as the core language it translates to.  What are we to do?  Convert all existing projects to C++?  Abandon and defunct those existing projects?

Maybe some kind of combined effort is the best solution, like having the __New Project__ menu give hardware choices (instead of language) and having a _default_ language automatically chosen for you based on the hardware selected.  That _default_ language can be shown on the __Your Project__ configuration page in a nondescript, demure way so as not to draw attention to it; and it can be limited to "supported" languages for that hardware (ie: fixed for now with the option for us to expand it in the future).

**Comment by DarkmatterVale** [comment]
I like the solution proposed by @PropGit. This simplifies the process for the user while still leaving the backend unchanged.

**Comment by DarkmatterVale** [comment]
I am going to close this because it has been changed throughout the site.
