### ISSUE TITLE
Write Help documents

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#36]

**Comment by DarkmatterVale** [comment]
Quick question. How should I organize the help files? Should I create separate files for each block? Or should I create separate files for each category? What if I did a mix of those two?

**Comment by michel-cf** [comment]
I think a mix of both is best. Complex blocks might need a seperate a
seperate file. While it's useless to put simple blocks in seperate files
(math blocks for example)

We could start by bundling them by sensor.

Don't forget to use anchors so that the page scrolls to the correct block
if you open it from an url.

**Comment by DarkmatterVale** [comment]
Ok. I will do that then.

Don't worry, I won't forget to add the links.

**Comment by DarkmatterVale** [comment]
I have a number of help pages, which you can see here: https://github.com/DarkmatterVale/BlocklyProp/tree/Help-Documents/help/textile/Spin

**Comment by DarkmatterVale** [comment]
@AndyLindsay,

Am I still going to be developing documentation for BlocklyProp? Or have I been kicked from working on that?

**Comment by michel-cf** [comment]
I can't speak about what you can do for the documentation. But in a meeting with Jeff it has been decided that all documentation files will be put into a separate repository.

This way it can be more easily be integrated into an offline version when needed. And is there more separation between code and documentation.

**Comment by DarkmatterVale** [comment]
Yes, I remember you mentioning that in one of the emails that I have received from either you or Mr. Martin.

Do we have any ideas as to what format they will be in? Markdown maybe?

**Comment by michel-cf** [comment]
I'dd prefer to keep them in textile as it is more powerful, even though it's less know as markdown.

**Comment by DarkmatterVale** [comment]
Sounds like a good idea then :thumbsup:

**Comment by michel-cf** [comment]
Closing as these will come in a separate repository

**Comment by DarkmatterVale** [comment]
Should I create a new repository and place the documentation I've created so far into them? Is that alright with you Mr. Lindsay and Mr. Martin?

**Comment by michel-cf** [comment]
It's easier if Jeff creates it instead of having to transfer it afterwards. And I also have to think about the directory structure as it should support multiple spoken languages, contain help for usage of BlocklyProp, using the blocks, explain generated code. And as such it's a bad idea to just start creating help files in a new repository.

**Comment by DarkmatterVale** [comment]
I see what you are saying. Definitely better to hold off then.
