### ISSUE TITLE
RGB OLED: Draw Circle

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#398]
I am going to submit a few drawing requests for the OLED, all of theses requests could be put into a single block with mutations. Until I learn how to make mutations I'll submit some as single blocks.

![draw](https://cloud.githubusercontent.com/assets/20099916/16925991/b0d73366-4cdb-11e6-84a6-703e8517dac0.PNG)

The empty spots in the block could default to a number of have a variable plugged in. Also, all colors will need to be included in the drop down, it is important that they are in all caps and they should automatically be assigned to ```int color```.

- WHITE
- PINK
- MAGENTA
- RED
- DARKRED
- REDORANGE
- LIGHTORANGE
- ORANGE
- YELLOWORANGE
- GOLD
- YELLOW
- LEMON
- YELLOWGREEN
- GREEN
- DARKGREEN
- GREENBLUE
- CYAN
- LIGHTBLUE
- SKYBLUE
- BLUE
- NAVYBLUE
- VIOLET
- PURPLE
- RASPBERRY
- TAN
- LIGHTBROWN
- BRONZE
- BROWN
- DARKBROWN
- LIGHTGRAY
- GRAY
- DARKGRAY
- BLACK

It if the checkbox IS marked it will generate the code:
```C
oledc_fillCircle(int x0, int y0, int r, int color);
```

If the checkbox is NOT marked it will generate:
```C
oledc_drawCircle(int x0, int y0, int r, int color);
```

Here is the link to the block in block factory: https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#y9zcgn

**Comment by MatzElectronics** [comment]
A color picker could be used, and then the oledc_color565() function can get it in the correct format:

**oledc_fillCircle(int x0, int y0, int r, oledc_color565(int RED, int GREEN, int BLUE));**  where RED, GREEN, and BLUE are 0-255.

**Comment by CarsonGracey** [comment]
@DarkmatterVale, would we be able to use blockly's default color picker and use its RGB values for this?

![color](https://cloud.githubusercontent.com/assets/20099916/16930789/9b776e48-4cf2-11e6-86e9-863f55e78205.PNG)

**Comment by MatzElectronics** [comment]
Should be albe to, look at my comment about masking and shifting - I've
done it in JavaScript before.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by MatzElectronics** [comment]
Here is the code for oledc_color565 - you could use the same math to
generate the r5g6b5 integer code directly in Javascript:

unsigned int oledc_color565(char r, char g, char b) {

unsigned int c;

c = r >> 3;

c <<= 6;

c |= g >> 2;

c <<= 5;

c |= b >> 3;


return c;

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by DarkmatterVale** [comment]
I'm not sure...Do I need to specifically list the colors available to the user, or can we just let them pick from the standard list of colors available?

**Comment by DarkmatterVale** [comment]
Ok so after looking up how to use color picker, I definitely think we can do that. However, I need the hexadecimal or RGB values for all of the colors you would like put into the color picker, as well as the number of columns (for colors) you would like to see when you select it.

**Comment by MatzElectronics** [comment]
I measured the color palette on the block factory, and it's a 7 column 10
row block.  Here are the colors (by row going across):

1
#FFFFFF
#CCCCCC
#C0C0C0
#999999
#666666
#333333
#000000

2
#FFCCCC
#FF6666
#FF0000
#CC0000
#990000
#660000
#330000

3
#FFCC99
#FF9966
#FF9900
#FF6600
#CC6600
#993300
#663300

4
#FFFF99
#FFFF66
#FFCC66
#FFCC33
#CC9933
#996633
#663333

5
#FFFFCC
#FFFF33
#FFFF00
#FFCC00
#999900
#666600
#333300

6
#99FF99
#66FF99
#33FF33
#33CC00
#009900
#006600
#003300

7
#99FFFF
#33FFFF
#66CCCC
#00CCCC
#339999
#336666
#003333

8
#CCFFFF
#66FFFF
#33CCFF
#3366FF
#3333FF
#000099
#000066

9
#CCCCFF
#9999FF
#6666CC
#6633FF
#6600CC
#333399
#330099

10
#FFCCFF
#FF66FF
#CC66CC
#CC33CC
#993399
#663366
#330033

Let me know if you have any questions,
Thanks!
Matt

On Jul 23, 2016 6:53 AM, "Vale" <notifications@github.com> wrote:

Ok so after looking up how to use color picker, I definitely think we can
do that. However, I need the hexadecimal or RGB values for all of the
colors you would like put into the color picker, as well as the number of
columns (for colors) you would like to see when you select it.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/parallaxinc/BlocklyProp/issues/398#issuecomment-234719333>,
or mute the thread

**Comment by zfi** [comment]
We are able to use the embedded color picker now. The value returned from the color picker has to be split into the R G and B components and those values submitted to oledc_color565(R, G, B). Not sure how that is going to work out for non-OLED devices.

**Comment by CarsonGracey** [comment]
Tested and Verified.

**Comment by zfi** [comment]
Pushed to master.
