### ISSUE TITLE
RGB OLED: Set Text Color

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#406]
This block with set the font color and the background (highlighting) to be used. 

![font color](https://cloud.githubusercontent.com/assets/20099916/16931850/e4fb4738-4cf7-11e6-868f-aa2ea0dbb352.PNG)

Parameters:
**c** 	Color of the font, in r5g6b5 format.
**b**	Color of the font's background, in r5g6b5 format. To make the background transparent, set to the same color as the font itself.

Code produced:

```C
oledc_setTextColor(	unsigned int c, unsigned int b);	
```

Here is the link to the block in block factory: https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#89gkbh

**Comment by zfi** [comment]
This probably cannot be verified until we have the OLED print block.

**Comment by kgracey** [comment]
OK, this works with a couple of caveats that have been addressed in other issues. As I'm not totally sure how to cross-reference things in GitHub, here are the things that need to change from my testing in SimpleIDE:

1. Include file colormath.h had to be renamed to colorMath.h
2. The block code that generates the `get8bitcolor` had to be renamed to [get8bitColor](url)

This issue can be closed since these items are addressed elsewhere.
