### ISSUE TITLE
Changes to XBee Block Code

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#410]
![xbee init](https://cloud.githubusercontent.com/assets/20099916/17002195/07b7a004-4e7f-11e6-8c18-0e139990d687.PNG)

This block needs two changes in its produced code to be fully functional.

### Blockly Code
```C
#include "simpletools.h"
#include "fdserial.h"

fdserial * xbee;



int main()
{
    xbee = fdserial_open(10, 12, 0, 9600);


}
```

The space between the * and xbee needs to be removed; ```fdserial *xbee``` instead of ```fdserial * xbee```.
Next, the DO and DI pin#'s need to be switched around since in the code, DI should be first and DO second in ```fdserial_open(rxpin, txpin, mode, baudrate);```. Currently the transmit and receive pins are reversed.

### Corrected Code
```C
#include "simpletools.h"
#include "fdserial.h"

fdserial *xbee;



int main()
{
    xbee = fdserial_open(12, 10, 0, 9600);


}
```

**Comment by wstodghill** [comment]
@CarsonGracey - Good catches! You guys are doing great work!

To be sure I understand, you are making sure the DI and DO pin# placement on the block is logically consistent with the fdserial.h order of placement for the rxpin and txpin variables. This is not just getting the right variable to the right spot, but so that students learn the order of input in a consistent fashion - is that correct? And also that the mode and baudrate variables are set automatically and so are not shown on the block, correct?

**Comment by CarsonGracey** [comment]
That's actually right, we could remove the IO pin choices for the S3 since they are always tied to 31 and 30. Also @wstodghill, we did have the block lock the baud rate at 9600 but we will make it so it can be selected in the future.

**Comment by wstodghill** [comment]
@CarsonGracey - Thanks!

**Comment by CarsonGracey** [comment]
Verified fixed
