### ISSUE TITLE
S3 Motor block problem 

### ISSUE THREAD

**Issue by RoxyH** [parallaxinc/BlocklyProp#413]
@dcarrier-parallax  When the time entered is over 8700, the robot goes backwards, but with any value under 8800. We verified this on Ken's robot. 
This code works 
![snip](https://cloud.githubusercontent.com/assets/20117435/17037737/3063bde4-4f47-11e6-8778-02aef300eb9f.PNG)
This code does not.
![snip 2](https://cloud.githubusercontent.com/assets/20117435/17037800/7923f4d6-4f47-11e6-8a70-431e83d58ad8.PNG)

**Comment by wstodghill** [comment]
@CarsonGracey - There was a maximum time limit of 5 seconds in the old GUI Program Maker  - BlocklyProp will have a maximum time limit of 15 seconds? What drives these limits? Is the issue in the Spin Object (don't know why...)?

**Comment by kgracey** [comment]
We have no specific reason why it was set at 15000 - we have asked @dcarrier-parallax to look into this and tell us what the maximum limits could be so we can continue to design our tutorials with this block fixed. 

@dcarrier-parallax - how about just setting this at 5,000 since we know it works? We can use the Delay block for longer wait times.

**Comment by kgracey** [comment]
This issue is closed, superseded by newer blocks.
