### ISSUE TITLE
Casting block(s)

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#430]
This will give users the ability to force BlocklyProp to set a variable to a specific type.

**Comment by kgracey** [comment]
What! Whoa! Another level of programming was just enabled.

**Comment by DarkmatterVale** [comment]
This should be ready for testing!

**Comment by kgracey** [comment]
@DarkmatterVale I made a small program to test this out. It seems to function properly with the choices being int and float, but when I choose char it displays the int value (maybe it should?) and the compiler chokes with char[128] because it is an array. 

![screen shot 2016-08-27 at 2 46 04 pm](https://cloud.githubusercontent.com/assets/9534148/18030275/fe9d83e0-6c64-11e6-9357-0579d907c2f1.png)

So I'm wondering about the implementation, and use of this block. The other blocks generally don't have support beyond int. It seems that introducing the casting ability may need to cause us to think further about implications in other blocks, but I'm not sure. A little bit of discussion from @zfi and @PropGit might be very useful. And we all need to keep in mind the target audience: students, probably younger ones, who've never ever seen much beyond integers. 

Should we hide the casting block for now, marking it for a future release to give us some time to figure out how we will use it?

**Comment by kgracey** [comment]
@DarkmatterVale is going to hide the casting blocks for now based on my comments above, so I will close this issue.
