### ISSUE TITLE
While does not support <= 

### ISSUE THREAD

**Issue by drpiccioni** [parallaxinc/BlocklyProp#434]
See my drpWhileTesting: Looks like while loops only work with <, not <=.  Note I am testing with an S2.  Thanks!

**Comment by kgracey** [comment]
@dcarrier-parallax this one is for you.

**Comment by DarkmatterVale** [comment]
Does this bug also exist in C?

**Comment by zfi** [comment]
@DarkmatterVale: The C implementation is also missing the '<=' comparison.

**Comment by DarkmatterVale** [comment]
I don't think I really understand the issue here. Below is a screenshot of a program I created in C using a while block.

![screen shot 2016-08-15 at 6 16 45 am](https://cloud.githubusercontent.com/assets/6094957/17661908/07116ece-62b0-11e6-9595-cbb7d590a2a7.png)

Can you please explain what needs to be changed?

**Comment by DarkmatterVale** [comment]
bump

**Comment by zfi** [comment]
Apparently everyone is in stunned silence over the recent development. That screenshot sure looks like what was reported as missing. I see it in the S3 block list too.

Closing this issue since it appears to be resolved.
