### ISSUE TITLE
Spin reserved words errors

### ISSUE THREAD

**Issue by zfi** [parallaxinc/BlocklyProp#437]
The array of reserved words in BlocklyProp/src/main/webapp/cdn/blockly/generators/spin.js line 45 contains 2 misspellings:
interger (should be integer)
bookean (should be boolean)

**Comment by PropGit** [comment]
I tried to test this (in [this project](http://demo.blockly.parallax.com/blockly/projectlink?id=115&key=6ad05182-5792-4b0e-acaf-e645554bb46c)) and am not sure I can actually test it properly.

It appears to automatically name-mangle under the hood (in the Spin code) so as to avoid the name conflict, but the code is also mangled to the point that it won't compile... probably because of a previous error with Spin implementation in BlocklyProp.

**Comment by dcarrier-parallax** [comment]
The reserved words list is also incomplete.  This issue should remain open until the entire list is extracted from the Propeller Manual.

**Comment by dcarrier-parallax** [comment]
The reserved word comparison is case sensitive, but the Spin tokenizer is not case sensitive, so it is possible to get reserved words past the filter by capitalizing them.

**Comment by PropGit** [comment]
This has been merged into demo.
