### ISSUE TITLE
SPIN Pin States Block Disparity

### ISSUE THREAD

**Issue by csavage-parallax** [parallaxinc/BlocklyProp#445]
I am seeing a disparity in the expected output of SPIN code to the following blocks:

![image](https://cloud.githubusercontent.com/assets/20691193/17194295/26678f72-540c-11e6-8459-5b7d0082a427.png)

```
PUB Start

  repeat
    OUTA[26]~~
    DIRA[26]~~
    waitcnt(clkfreq / 1000 * 1000 + cnt)
    OUTA[26]~
    DIRA[26]~~
    waitcnt(clkfreq / 1000 * 1000 + cnt)
```

Setting the pin state should not set the direction register at the same time. When a pin is set high or low the corresponding SPIN code seems to contain a direction set as well. However the same block set the toggle does not set the pin direction and therefore the output does not actually toggle.

IMO we should have an input and output mode and allow the pin state changes to work as they would in SPIN rather than high and low working like PBASIC.

**Comment by PropGit** [comment]
Actually, we decided that things like Toggle should set the state and direction; if that's not the case here, we need to fix it.

I see your point with _make pin_ though... unless there's another way to set the pin state (only), the _make pin_ is naturally the only way to do that.

Ultimately, we want blocks that affect pin state (in general) to ensure that it is also set to an output, because that's the intent of the user most of the time.  Setting a state without affecting direction is an advanced concept that may not be appropriate for BlocklyProp users.

More thought needs to be applied here before making any changes.

**Comment by dcarrier-parallax** [comment]
These blocks are no longer available in Spin, so I am closing this issue.
