### ISSUE TITLE
Drive block does not work

### ISSUE THREAD

**Issue by RoxyH** [parallaxinc/BlocklyProp#450]
The code will compile and upload but the robot remains unmoved. 
![capture 4](https://cloud.githubusercontent.com/assets/20117435/17228835/adb91b7c-54c9-11e6-90df-3fc09dfd16d6.PNG) 
Here's the project link
http://demo.blockly.parallax.com/blockly/editor/blocklyspin.jsp?project=136#

**Comment by kgracey** [comment]
@dcarrier-parallax

**Comment by wstodghill** [comment]
Just tested all the current drive blocks current - 07/29/16 - 12:12 a.m. Central Time. All blocks worked. See the code named **_Drive Play - S3 Robot - WORKS! Thanks David!_** at this link [http://demo.blockly.parallax.com/blockly/my/projects.jsp#105](http://demo.blockly.parallax.com/blockly/my/projects.jsp#105) 

Thanks to David and Ken for pursuing this so diligently! Time to get busy!

**Comment by wstodghill** [comment]
@RoxyH - See "Test RoxyH #450" I added a Green go LED and Red done LED - otherwise identical code and works great. I think David got it when he update the "wrapper"! See [http://demo.blockly.parallax.com/blockly/my/projects.jsp#140](url)

@dcarrier-parallax - You sir, are a steely-eyed programming man! Thank you! [https://en.wikipedia.org/wiki/John_Aaron](url)
