### ISSUE TITLE
RGB OLED: Get MaxHeight/Width

### ISSUE THREAD

**Issue by CarsonGracey** [parallaxinc/BlocklyProp#476]
So after programming the OLED display in SimpleIDE a bit, I realized I used ```oledc_getWidth()``` and ```oledc_getHeight()``` multiple times. For example I was just placing a circle in the center of the display and I found it was easiest like this:

 ```C
oledc_fillCircle(oledc_getWidth()/2, oledc_getHeight()/2, 30, oledc_color565(130, 120, 110));
```

Would it be beneficial to add these two blocks into the OLED category? It would make cutting the screen into halves or thirds or anything quite easy. Is there an easier way to do this that I am missing?

![image](https://cloud.githubusercontent.com/assets/20099916/17416438/ff802346-5a42-11e6-98d0-871c49d6e2ef.png)

![image](https://cloud.githubusercontent.com/assets/20099916/17416455/12f62a4c-5a43-11e6-98a3-0adc6492f8db.png)

**Comment by PropGit** [comment]
@CarsonGracey - I can relate, I've found the frequent need to do such things in other programming environments for other devices too.  Those blocks can be really helpful here, I agree.

**Comment by zfi** [comment]
Notes on the implementation of these blocks:

Blockly.propc.oled_get_max_height = function() {
  [...]

    // Emit code to clear the screen
    var code = 'oledc_getHeight()';
    
    // This line causes a zero to be embedded in the resulting 'C' code:
    // Note the lack of square braces.
     return code;
    
    // Return function call without surrounding parens:
    //   oledc_drawPixel(oledc_getHeight(), ..., ...);
    return [code];
    
    // Return function call with surrounding parens:
    //    oledc_drawPixel(..., (oledc_getWidth()), ...);
    return [code, Blockly.propc.ORDER_NONE];

Can someone offer an explanation for the different behaviors?

**Comment by DarkmatterVale** [comment]
Interesting discovery with the second return statement...I didn't know about that.

When a block has an output (which is defined by whether the code ```this.setOutput(true, '...');``` is included in the UI generation), you must specify how you would like the output to be formatted. The first return statement applies no formatting, but cuts the output so that only the first character is returned. This is why you get an "o" (not a zero) with the first return statement. The second return statement is what you should be using (since I did not know that you could not include a second argument I always used Blocky.propc.ORDER_NONE). This applies no formatting, but leaves the original output intact. The final adds parenthesis around the output.

**Comment by CarsonGracey** [comment]
Tested and Verified.

**Comment by CarsonGracey** [comment]
It may be better if we rename the blocks to "max height" and "max width"

**Comment by DarkmatterVale** [comment]
I agree that better conforms with our other standards for blocks

**Comment by CarsonGracey** [comment]
Tested and Verified.
