### ISSUE TITLE
New "S3 Robot Project" Project (not Spin) on landing page

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#491]
@michel-cf please change the text on the Blockly landing page from "Spin Project" to "S3 Robot Project" and change the graphic underneath from a Spin icon to the S3 robot. Specifically:

![screen shot 2016-08-10 at 3 58 21 pm](https://cloud.githubusercontent.com/assets/9534148/17573763/611532fe-5f11-11e6-92e6-47ef189c8694.png)

We realize this is a short-term solution and far from ideal. But for now it should at least get S3 users working in the right direction. 

Here's a graphic of the S3 for you:

![s3-top](https://cloud.githubusercontent.com/assets/9534148/17573833/da223d22-5f11-11e6-8193-aa5210354a24.png)

If you have a better way of dealing with this we're open to other solutions.

**Comment by wstodghill** [comment]
I like this idea! It reflect more of what we are actually doing...

**Comment by DarkmatterVale** [comment]
Has someone tackled this yet?

**Comment by zfi** [comment]
This change should appear on the Demo site in about 5 minutes.

**Comment by wstodghill** [comment]
Saw the change at the bottom of the page - and that it still lists this as a new Spin program with a Spin Icon (rather than the S3 Icon). I think that is okay - but since Spin is not directly generated (it is a bit confusing). What about at the upper tool bar too - under New projects is this choice...

![new project](https://cloud.githubusercontent.com/assets/8891440/17940355/4c52ea30-69f4-11e6-8043-fb7338cddc54.JPG)

**Comment by DarkmatterVale** [comment]
@wstodghill #568 Fixes that last one :D

**Comment by kgracey** [comment]
Yep. This seems to have been implemented.

**Comment by wstodghill** [comment]
Once I cleared my cache - all became clear!

**Comment by zfi** [comment]
Mind blown
