### ISSUE TITLE
S3 blocks: variables and constants

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#520]
@dcarrier-parallax we no longer have variable and constant blocks in the new S3 blocks [and need them].

**Comment by wstodghill** [comment]
There are lots of other blocks lost in the last move too. Is this the plan or just something that happens during an update. Many of my previously written projects lost pieces or are not gone completely due to loss of blocks in the S3 group. I hope we retain all those "other" ways to do things! Many were very powerful.

**Comment by kgracey** [comment]
Hate to ask, but which blocks?

**Comment by wstodghill** [comment]
I do not know our plans, but I just went to http://blockly.parallax.com/blockly/ and pulled at least these - though a few made the move (I think the variables are there now...) - can't compare since Beta Demo is down this a.m.

![controlblocksback](https://cloud.githubusercontent.com/assets/8891440/17643784/c9d8a526-6139-11e6-9f1b-897e98b688e5.JPG)

![operatorsblocksback](https://cloud.githubusercontent.com/assets/8891440/17643785/cbdea9b0-6139-11e6-8139-8a4ede5e12e7.JPG)

![functionsblocksback](https://cloud.githubusercontent.com/assets/8891440/17643786/cdd9e248-6139-11e6-82bc-78db6361715b.JPG)

![variablesblocksback](https://cloud.githubusercontent.com/assets/8891440/17643787/d0133a64-6139-11e6-9bea-94e7d7a63ac8.JPG)

![actuatoroutpotblocksback](https://cloud.githubusercontent.com/assets/8891440/17643788/d1fb5cf8-6139-11e6-88b3-59482d8074ae.JPG)

**Comment by wstodghill** [comment]
Separate set volume block is gone too...

**Comment by wstodghill** [comment]
Now that BlocklyProp is up I looked and the following are our current choices - this is what we have right now on 081316 am

![s3controlblocks081316am](https://cloud.githubusercontent.com/assets/8891440/17644077/a515c65c-6142-11e6-88f7-ac7885514e38.JPG)

![s3mathblocks081316am](https://cloud.githubusercontent.com/assets/8891440/17644078/a7c9312c-6142-11e6-9b96-c1a707079e80.JPG)

![s3variableblocks081316am](https://cloud.githubusercontent.com/assets/8891440/17644079/a9f091ac-6142-11e6-9f96-08416d4d9666.JPG)

![s3sensorslineblock081316am](https://cloud.githubusercontent.com/assets/8891440/17644080/abcb5976-6142-11e6-903a-e47a980a321c.JPG)

![s3sensorsobstacleblocks081316am](https://cloud.githubusercontent.com/assets/8891440/17644081/adc57ab8-6142-11e6-932a-3cf4b71a7320.JPG)

![s3sensorslightblocks081316am](https://cloud.githubusercontent.com/assets/8891440/17644083/af7f794e-6142-11e6-8b48-44813b394c16.JPG)

![s3sensorsstallblocks081316am](https://cloud.githubusercontent.com/assets/8891440/17644084/b12f791a-6142-11e6-97c9-349ff8a047d2.JPG)

![s3sensorsbuttonblocks081316am](https://cloud.githubusercontent.com/assets/8891440/17644085/b2cf691a-6142-11e6-9471-635f4406c781.JPG)

![s3actionsmotorsblocks081316am](https://cloud.githubusercontent.com/assets/8891440/17644086/b4190ad8-6142-11e6-9f61-95782abb9a9c.JPG)

![s3actionsmotorsblocks081316am 2](https://cloud.githubusercontent.com/assets/8891440/17644087/b615879e-6142-11e6-9b19-0b4c41ffc239.JPG)

![s3actionssoundblocks081316am](https://cloud.githubusercontent.com/assets/8891440/17644088/b7ac5d44-6142-11e6-9282-b1b90753f1d3.JPG)

![s3actionsledsblocks081316am](https://cloud.githubusercontent.com/assets/8891440/17644089/b90708a6-6142-11e6-8ee9-48bee4f82ddb.JPG)

![s3actionscommunicateblocks081316am](https://cloud.githubusercontent.com/assets/8891440/17644090/ba9c4e10-6142-11e6-921f-bb20810db21e.JPG)

Many lost items are still elsewhere in Blockly - hope can get some of them back to the S3 set!

**Comment by DarkmatterVale** [comment]
There were some merge issues yesterday. @zfi can you please take a look?

**Comment by kgracey** [comment]
Several issues here, but mostly addressed.
