### ISSUE TITLE
Current Release Plan

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyProp#54]
What is the current release plan with dates?

**Comment by michel-cf** [comment]
There is no release plan. Unlike commercial projects, we work on this project whenever we have time.

Having targets and release dates will both force us to spend more time (that we might not have) and demotivate us when we don't finish on time.

So, no milestones and please, don't use the issues list as a ideas list. Making this list so long also demotivates, because it never gets shorter.
