### ISSUE TITLE
How to use the master branch

### ISSUE THREAD

**Issue by michel-cf** [parallaxinc/BlocklyProp#549]
As mentioned in #433:

Why are you struggling all the time with that master branch. Why don't we wait until we get a tested version and then push everything to master at once? (If needed with an acceptance stage in between)
Then you can close all the tickets when they are validated in demo.
This way of merging everything individually (, and out of order) just introduces more chance for merge issues.

**Comment by DarkmatterVale** [comment]
I answered your question in #443.

**Comment by PropGit** [comment]
@DarkmatterVale - Let's continue the conversation here.

@michel-cf and @DarkmatterVale - our demo branch has diverged from master so much (so long) that commit-group merges into master are a nightmare because of many conflicts.  This is because development was running at a swift pace with no scheduled sprints with managed merges at their end. 

What we need to do is a big merge (or rather replacement) of the tip of master with a perfect state of demo (tip) and then apply any other changes that may have occurred in master to that.  I've combed through the commit history since June 30th when we created demo to verify that this certainly appears to be the easiest way to solve it... there are very few changes in master that don't exist in demo.

To make this smooth, we need to finish existing feature work and merge it into demo successfully, then everybody take a rest, I'll make the switch, then we can carry on from a new point on master and demo using a sprint-based method.

@DarkmatterVale - 

- The history messiness is no longer a concern to us, all things considered, and this solution I'm driving towards will not mess up the visible history of master; it will be a full commit that sets tip of master to the contents of the tip of demo.
- Having the tip of demo reflect unwanted features from unwanted commits is the thing we need to avoid.  I don't believe we have this condition right now.  Can you confirm?  Are there really any unwanted aspects in demo (tip) right now that are due to unresolved commits?  If so, we need to revert those commits before this big move.

**Comment by DarkmatterVale** [comment]
@PropGit I will look, but the problem I see is that there could be blocks that have had merge issues which revert them back to pre-fix state. This is a common issue (just take a look at the comment block...) and to fix it we will have to go through a lot of the closed tickets to ensure the blocks are not broken.

**Comment by PropGit** [comment]
@DarkmatterVale - That's exactly what I was worried about too.  I think I've seen a few of them.  Since you've noted that, I'll go through the history on demo more carefully today to find and note those things.  Most I can figure out, but some I will need your help in confirming or denying that it's a problem.  I know you're busy and maybe can't afford any more time on this, this week.  If you can, @zfi and I really want to make this move before mid-day 8/19 so we can try to build and deploy Production for a week's-worth of usage/tests.  Don't stress, just let me know what is practical from your side and we'll work it out.

**Comment by DarkmatterVale** [comment]
Here is what I know is incorrect. I'd recommend NOT messing with the history; just leave it and append new commits to fix the broken things. In the future we can worry about keeping a clean history....

1) Comment block : wrong text (see master branch for correct version of code)
2) Values blocks : two of the blocks within the Values category are colored incorrectly

I think that's all...

**Comment by DarkmatterVale** [comment]
I'm going to close this since the new process has been thoroughly documented within the BlocklyProp developer's guid

**Comment by DarkmatterVale** [comment]
Oh I guess I can't close it?
