### ISSUE TITLE
New Communicate Blocks Don't Invoke Serial Terminal

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#605]
The new Communication category blocks (__new line__, __clear screen__, __move to column__, and __move to row__) need to invoke the serial terminal;
```
/* SERIAL_TERMINAL USED */
```
just like the blocks __print " "__ and __print value__ do.

**Comment by MatzElectronics** [comment]
Tested and Verified-ish...

These blocks:
![image](https://cloud.githubusercontent.com/assets/19737272/18069028/49882a1e-6df9-11e6-8b65-d1f8ad2bfe03.png)

Generated this output:
![image](https://cloud.githubusercontent.com/assets/19737272/18069012/32939410-6df9-11e6-9e60-8a305222bd34.png)

The problem is that it's not exactly row 2 and 10 - instead it's relative to the info at the top of the screen.  If I cleared the screen first, I'm sure it would have worked well.

Is is possible to move that connection information out of the terminal area into its own box?:
![image](https://cloud.githubusercontent.com/assets/19737272/18069238/896f0282-6dfa-11e6-831b-97d639051770.png)

**Comment by PropGit** [comment]
Tested and verified also.

**Comment by PropGit** [comment]
NOTE: I continued @MatzElectronics conversation in Issues #626 and #628.
