### ISSUE TITLE
Terminal - Letter+Hyphen+NumberOrLetter Creates New Line

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#632]
A letter followed immediately by a hyphen and another letter or number (and maybe more) causes an apparent new line to be injected before the hyphen.

![image](https://cloud.githubusercontent.com/assets/1266318/18073053/e6fc0b76-6e17-11e6-8413-436f923d212d.png)

Here's the program to test it:  http://demo.blockly.parallax.com/blockly/projectlink?id=325&key=fe68ef91-b7e9-49e2-8ed4-07bf1a454019

**Comment by MatzElectronics** [comment]
Anything adjacent to the hyphen will break the line - because HTML won't render consecutive spaces, the empty space is filled with "&nbsp;" (non-breaking space) characters.  This is the same as if they were letters or other characters - you can replicate the behavior in a word processor - type something like:

"aaaaa-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"... until the end of the line, and it will wrap at the hyphen.

I think that the solution is to replace the hyphen with a "non-breaking" hyphen.  I'll submit a PR for this soon and reference this issue.
