### ISSUE TITLE
learn.parallax correction

### ISSUE THREAD

**Issue by michel-cf** [parallaxinc/BlocklyProp#687]
On: http://learn.parallax.com/tutorials/robot/scribbler-robot/getting-started-blocklyprop-s3/setting-blocklyprop-s3

It states:

> You’ll see a page with two right-hand links. Notice it says, “The BlocklyProp-client loads your applications into the Propeller chip on the S3 and allows you to have a serial terminal in your browser connected to your Propeller.”  There are selections for MacOS and Windows (64 bit) - you can run an executable program installer or download a zip to store and use on your computer (You may have to click on "Show clients for all operating systems" to see Mac download options).

The last sentence: ` (You may have to click on "Show clients for all operating systems" to see Mac download options).` should not be really the case.

The feature where the download links is shown, has operating system detection, and shows the correct downloads for the user's operating system. Meaning that on Mac you should see the MacOS downloads, and need to click on "Show clients for all operating systems" to see those for Windows.

**Comment by PropGit** [comment]
Thanks @michel-cf.

@ Learn Dev Staff: The proper client will be shown for Win and Mac users if they are on a Win / Mac system, respectively.  The "Show clients for all operating systems" link is only there for those that want to download (or see) clients for other operating systems that they are currently not using.

The fix is probably to just leave off the "Show clients..." statement, as it's for a rare, advance user situation.

**Comment by PropGit** [comment]
Corrected.  Thanks again.
