### ISSUE TITLE
Discussion/Request Array variables

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#701]
How difficult would it be to do arrays?  I'm starting to get a handle on how the stuff behind the scenes works, so I'm confident the blocks can auto-detect when they are dealing with strings (char arrays) versus int arrays.

**Comment by DarkmatterVale** [comment]
Arrays are a tricky situation...I'm not really sure how difficult it would be to implement them, but here are my thoughts up to this point:

1) A new array variable block will need to be created. Since variables are built into the core of Blockly, I have no idea how much work it will take for this to be implemented
2) Auto-detection of arrays will be impossible in many cases. This is due to the fact that Blockly will have no context for what a function (within the C program) will return. If you add an array variable block, you can enable manual setting of arrays, but as stated above, I'm not sure how much work that will take to edit Blockly.

The current algorithm used to detect integers/chars is a pretty simple one. You can find it at https://github.com/parallaxinc/BlocklyProp/blob/master/src/main/webapp/cdn/blockly/generators/propc/variables.js#L130 and https://github.com/parallaxinc/BlocklyProp/blob/master/src/main/webapp/cdn/blockly/generators/propc.js#L211

The only other way I can think of creating array variables is to add support for them with the casting block (or another non-variable block). This will break integration with the inner Blockly variable system, but might be a lot less work to develop.

**Comment by MatzElectronics** [comment]
Okay, that's helpful, thanks.  I'm thinking that we should not try to have it do much automatically.  For strings, I think a few blocks that allow you to set and retrieve specific characters in the char array are all we need, since variables that hold strings are already arrays.  Then, a block that is effectively a "new number array" that lets you set and retrieve ints from it would be enough.  

What I don't want to happen is have int arrays show up in the other variable dropdowns.  I would, however, like dropdowns in the set/retrieve from array blocks that provide a list of arrays (char or int) - is there a way to filter the variables that end up in those dropdowns?

I'll put it on my to do list.  I'll definitely need some help, but I can draft the initial blocks.

**Comment by MatzElectronics** [comment]
Maybe this provides a clue: https://developers.google.com/blockly/guides/create-custom-blocks/dropdown-menus

**Comment by MatzElectronics** [comment]
Closing this for now - we aren't ready for the complexity, and for the game I was thinking of, we'll use EEPROM, which might be a good way to introduce memory anyway.
