### ISSUE TITLE
Windows 7 32bit support

### ISSUE THREAD

**Issue by michel-cf** [parallaxinc/BlocklyProp#709]
Apparently there is request for Windows (7) 32bit support.

I only have access to a Windows 8 32bit system, and I'm unsure about backwards compatibility.

@pjewald @PropGit Does Parallax have a system where we can make a build of the BlocklyPropClient/Propeller-communicator?

**Comment by PropGit** [comment]
For development systems I've used, backward compatibility has not been a problem unless you're specifically using a Windows feature that doesn't exist in a previous version of Windows.

If your Windows 8 32-bit system doesn't end up working for this, then yes, we can build it.  Either way, I can test it back to Win XP 32-bit once it's built.

**Comment by kgracey** [comment]
I've got one but we can ask the customer too. KG

**Comment by kgracey** [comment]
What kind of schedule do you have for creating the installer, Michel? I'll get back to the customer.

**Comment by michel-cf** [comment]
I'll try to fix #227 first, so that we don't need to update it after a few days.

Unless I get unexpected problems I'll try to fix it by Wednesday.

**Comment by michel-cf** [comment]
It seems my Windows 8 32bit system makes builds that are not backwards compatible with Windows XP/Windows 7 32bit

Someone else, with an older version of Windows will have to make these builds.
Install Python 2.7: https://www.python.org/ftp/python/2.7.12/python-2.7.12.msi (Default location: c:\Python27
Install PyCharm community edition
Check out the demo branch from the BlocklyPropClient repository
Add packages: ws4py, CherryPy, pyserial, pyinstaller

From the repository directory run command line command:
c:\Python27\Scripts\pyinstaller BlocklyPropClient.windows.spec

**Comment by PropGit** [comment]
@michel-cf - What am I supposed to see after running the specified command line?  There was a lot of output that seemed proper and no noticed error messages.  Now what?  Am I supposed to just run the BlocklyPropClient.exe that's in the build subfolder?

I don't see the other files (like the mscv.. dlls).

**Comment by michel-cf** [comment]
The output you want is in the dist subfolder, the build subfolder only contains intermediate files.

**Comment by PropGit** [comment]
__[UPDATE]__ it's the _dist_ subfolder that I was after.

**Comment by PropGit** [comment]
@michel-cf - I've built this using your instructions on both Win 7 64-bit and Win 7 32-bit now.  
- The 64-bit version works.
- The 32-bit version still reports "The program can't start because msvcr100.dll is missing from your computer."

I could predict that it was going to fail because the build process says this near the start (see __bold__ lines).  Strangely, the "90" version of those dependencies are what is used on 64-bit Windows, but the supposed 32-bit version is looking for "100".

> C:\Users\jmartin\PycharmProjects\BlocklyPropClient>pyinstaller BlocklyPropClient
.windows.spec
1475 INFO: PyInstaller: 3.2
1498 INFO: Python: 2.7.12
1510 INFO: Platform: Windows-7-6.1.7601-SP1
1512 INFO: UPX is not available.
1523 INFO: Extending PYTHONPATH with paths
['C:\\Users\\jmartin\\PycharmProjects\\BlocklyPropClient']
1526 INFO: checking Analysis
1527 INFO: Building Analysis because out00-Analysis.toc is non existent
1527 INFO: Initializing module dependency graph...
1531 INFO: Initializing module graph hooks...
1597 INFO: running Analysis out00-Analysis.toc
__1615 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
  required by C:\Python27\python.exe__
__3509 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1
fc8b3b9a1e18e3b_9.0.30729.1_none_8550c6b5d18a9128.manifest__
__3523 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1
fc8b3b9a1e18e3b_9.0.30729.4148_none_f47e1bd6f6571810.manifest__
__3538 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1
fc8b3b9a1e18e3b_9.0.30729.4940_none_f47ed0f6f6564d90.manifest__
__3627 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.30
729.4940_none ...__
__3629 INFO: Found manifest C:\Windows\WinSxS\Manifests\x86_microsoft.vc90.crt_1fc
8b3b9a1e18e3b_9.0.30729.4940_none_50916076bcb9a742.manifest__
__3634 INFO: Searching for file msvcr90.dll__
__3636 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_
9.0.30729.4940_none_50916076bcb9a742\msvcr90.dll__
__3639 INFO: Searching for file msvcp90.dll__
__3641 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_
9.0.30729.4940_none_50916076bcb9a742\msvcp90.dll__
__3643 INFO: Searching for file msvcm90.dll__
__3646 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_
9.0.30729.4940_none_50916076bcb9a742\msvcm90.dll__
__3732 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1
fc8b3b9a1e18e3b_9.0.30729.1_none_8550c6b5d18a9128.manifest__
__3736 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1
fc8b3b9a1e18e3b_9.0.30729.4148_none_f47e1bd6f6571810.manifest__
__3740 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1
fc8b3b9a1e18e3b_9.0.30729.4940_none_f47ed0f6f6564d90.manifest__
__3742 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0,
 30729, 4940)__

**Comment by PropGit** [comment]
The files emitted by the two builds are very similar.  The manifests even specify "90" of the msc dependencies in both cases, so I don't know why the executable is looking for v"100" of them.

**Comment by PropGit** [comment]
Solved it, thanks to @zfi - PyInstaller 3.2 was compiled with VS 2010 but python 2.7 used previous version... the newer installer introduces the v100 dependency.  See [this thread](https://github.com/pyinstaller/pyinstaller/issues/1974).  Apparently they've fixed it for the next release, but that release appears to not be available yet.

Downgrading the PyInstaller package to v3.1.1 builds the package properly on Win 7 32-bit.  It seems that the 32-bit and 64-bit versions must be built on the respective OS hosts (however the 32-bit will likely work on both 32 and 64-bit machines).

**Comment by PropGit** [comment]
@michel-cf - I sent you links to the 32-bit and 64-bit _dist_ files, built on 32-bit and 64-bit Win 7 VMs with PyInstaller v3.1.1 package.

**Comment by PropGit** [comment]
Here's final (hopefully) 32-bit and 64-bit BlocklyPropClients v0.5.  They should work on Win7, 8, 8.1, and 10.
- [BlocklyPropClient-setup-32.exe](https://db.tt/hFOKhkUC)
- [BlocklyPropClient-setup-64.exe](https://db.tt/v8ibWNmF)

**Comment by zfi** [comment]
Are these new clients ready to deploy into production?

**Comment by PropGit** [comment]
@zfi - I was waiting for testing results from customers, have have received none.  I thought of something this morning that would allow me to directly test it... I'll do that right now.

**Comment by PropGit** [comment]
@zfi - I tested both 32-bit Client and 64-bit Client on a 64-bit host (Win 7).  Both work perfectly.  I doubt there'd be any problem with the 32-bit on a 32-bit client... let's publish them!

You can get them both from the [links in the post above](https://github.com/parallaxinc/BlocklyProp/issues/709#issuecomment-250226808) or from your Staff/BlocklyProp Client folder.

Deploy both because it's a new version (v0.5) of each.

**Comment by zfi** [comment]
Links updated on Demo. Will add this to the staging checklist for production.
