### ISSUE TITLE
Login / Register - Convert to Overlay?

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyProp#72]
Can the Log in (../blockly/login.jsp) and Register (../blockly/register) pages be converted to an overlay-type view like the "You are not logged in" prompt is shown?

![image](https://cloud.githubusercontent.com/assets/1266318/11083623/6f59c382-87e6-11e5-8828-e9ee783ecea7.png)

**Comment by michel-cf** [comment]
Although possible, it's a major change.

Current setup:
- page is created on server with links to the full editor and some meta information, if you are not logged in, the html and javascript for the "You are not logged in" dialog is added.
- On page load, this javascript changes the links to the editor so that the editor is opened
- if you click on "try", the original url is changed to the demo editor
- if you click on login, you are sent to the full editor, but the server security library redirects you to the login page, after login, it sends you to the full editor that was requested

Changing this so that the login and registering is done in a dialog presents a few challenges:
- I'm not sure if I can use the current authentication mechanism, as that one redirects you to a page after login, instead of returning some json for the ajax call
- It will require a major rethink of the current system

**Comment by jeffam70** [comment]
@michel-cf - okay, we don't want to introduce so much work for an item like this.

Overall, the thing that really struck me is that the log in and registration fields seem to be somehow right-justified on the browser window (but not all the way to the right edge).  If we can restyle that (along with other things on those pages) so that the group is horizontally centered in the page, it'd probably be very pleasing.

**Comment by michel-cf** [comment]
The current layout is:
Fixed width, 2 columns with the login/registration for in the right column.

The intention was to add an accompanying text in the left column.

**Comment by PropGit** [comment]
Thanks.  I understand and am closing this issue.
