### ISSUE TITLE
S3 rotate servo, disable servo block, Ping block and Scribbler.Start call

### ISSUE THREAD

**Issue by wstodghill** [parallaxinc/BlocklyProp#722]
@PropGit -  Can someone explain how these blocks are intended to function?

I have been using the blocks experimentally. When I do. the blue power on LED on the S3 stops working - is this a bug or does the use of hacker port pins disable the function of this LED? 

Is the disable servo block required to stop the function of the pulse being sent to the servo. Even followed by a wait block, the servo got warm (as if it where still receiving a hold? 

Can someone clarify or test this so we can figure out if we have a problem? I discussed this a bit with @kgracey and he was not certain of the answer.

**Comment by wstodghill** [comment]
Ping))) in hacker port also makes the blue power LED on the S3 stop working. I guess this use of the the hacker port pins is effected by the assignment of hacker port pins.

**Comment by wstodghill** [comment]
Ben Wirz wrote 
"I’m just guessing here since I don’t have access to the wrapper spin files but the generated spin code in your program does not include a Scribbler.Start call which is required in initialize the scribbler object which makes the LED work correctly.

For testing, try adding a short drive command to your program and see if its starts working.  If I’m right then this is a bug in the Blockly program.  It always include the Scribbler.Start command.

-Ben


Your Setup Section is:

PUB Setup
  Scribbler.ServoStart
  Start

It should be probably look like this:

PUB Setup
  Scribbler.Start
  Scribbler.ServoStart
  Start"

Ben also note the abcense of the problem on some code Ken wrote which did inclued the Scribbler.Start (it has some motor blocks

This solves the blue power LED issue and was tested by me this morning,

@PropGit - can we get the wrapper to catch this for the rotate servo, disable servo and Ping))) blocks?

**Comment by PropGit** [comment]
@wstodghill - I believe you are right; good detective work.  

Proposed Resolution: The __Rotate Servo__ and __Disable Servo__ blocks need to include the Scribbler.Start call.

The "Scribbler Wrapper" object is called "Block_Wrapper.spin" and can be found in the Scribbler-3_Library repo here:  https://github.com/parallaxinc/Scribbler-3_Library/blob/master/Block_Wrapper.spin

**Comment by wstodghill** [comment]
@PropGit - Ben Wirz and Ken are the real detectives. I'm more like Dr. Watson, the bumbling sidekick, reporting on the work of others! Thanks for the link.

**Comment by dcarrier-parallax** [comment]
I am unable to duplicate your issues with the 'disable servo' block.  Can you verify that the servo is still getting a signal after calling the block?  Try using a continuous-rotation servo; it will stop spinning without a signal.

Regarding the power light, it only turns on if the Scribbler object is started, but the servo blocks do not use any of the functionality in the Scribbler object, so without any other Scribbler-specific blocks, nothing will turn on the power LED.  It would be inappropriate to load the Scribbler object for the servo, and such a workaround would be required on every non-Scribbler Spin block.

Ideally, the power/charge controller firmware would turn the power LED on appropriately, so that a halted program would not affect the state of the LED, but it appears only the LED near the lightning '🗲' symbol is controlled by the power/charge controller.

As a workaround, it may be possible to load the Scribbler object, and run the code to turn on the LED, when the user has selected the 'Scribbler Robot' as the board type, regardless of which blocks they are using.

**Comment by wstodghill** [comment]
@dcarrier-parallax 

Not problem on not turning on the power LED - just wanted to understand why. That way we can explain why it is off - if no other S3 functions are called by the blocks.

I was also asking about the disable servo. What I was saying is that without using it, even if I supply a time for servo move - the signal seems to continue to be sent - So (again to explain to folks) - we can tell people why to use the disable servo block always.  That is why I asked someone to explain how they were inteded to work. No problem here - just want to provide good instructions for proper use.

**Comment by wstodghill** [comment]
@PropGit - Wonder if this could be closed - since it seems to do what we agree we want...

**Comment by zfi** [comment]
@dcarrier-parallax: Can you verify that the resolution proposed by @PropGit above was actually implemented? I cannot seem to locate the blocks he noted in 

>Proposed Resolution: The Rotate Servo and Disable Servo blocks need to include the Scribbler.Start call.

**Comment by dcarrier-parallax** [comment]
The proposal to include the Scribbler.Start call in a block for non-Scribbler hardware will not be implemented.  After further research, it is apparent that the indicator labeled with the lightning '🗲' symbol functions as both charge and power indicators, but it currently only shows the power status while the Scribbler robot is not connected to a USB host or charger.  The power status indication cannot be solved in Propeller code, because the Propeller microcontroller is not always running while the Scribbler robot is powered on.

We have requested that future builds of Scribbler robots include a charge controller firmware modification, to indicate the power status while the Scribbler robot is connected to a USB host or charger.

**Comment by zfi** [comment]
@dcarrier-parallax: What you said makes sense for non-Scribbler hardware. Does this also apply to Scribbler hardware?
