### ISSUE TITLE
Right click brings up the standard menu

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#725]
When you right click a block, the standard menu is coming up, covering up the blockly menu we want to see:

![image](https://cloud.githubusercontent.com/assets/19737272/18725972/42444b2e-7ff7-11e6-82cb-b609f1d5f2b8.png)

**Comment by DarkmatterVale** [comment]
I'm not able to reproduce this on Safari 9.1.1 on both the production and demo server. You might be seeing this issue because you were not previously "in" the window (even though the block is highlighted. If you left click in the workspace then proceed to right click on the block does it fix this issue?

**Comment by MatzElectronics** [comment]
It appears to be exclusive to Chrome on Mac.  Chrome in Windows is ok.  It doesn't appear to be an issue of focus as you suggested, it happens regardless - every time I right click a block or the workspace.

**Comment by MatzElectronics** [comment]
I figured this out finally - it happens if you zoom out (75%-ish or less) which I have been doing to fit more blocks on the screen at once.  I think it's outside of our control and not really worth addressing - I'm not sure we can do anything about it.  It just helps to know why :)

**Comment by wstodghill** [comment]
@MatzElectronics said, "It just helps to know why :)"  - Yes, it does. It always does.
