### ISSUE TITLE
Reduce vertical height of "description" box to one inch (a few cm)

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#770]
Student and school notebooks often have lower resolution and they are unable to see the "next" button because it is so far down the screen due to the vertical length of the description box. We should shorten the height of this box to something quite small so they can find the button and proceed to the next screen. 

![screen shot 2016-10-11 at 1 04 48 pm](https://cloud.githubusercontent.com/assets/9534148/19286607/22d61954-8fb3-11e6-8e6f-600db6f4ae4c.png)

**Comment by MatzElectronics** [comment]
If we monkey with this - let's remove the "Basic Project Info" text, since
it seems redundant, and make it stop requiring you to put something in the
description box.

*Matthew Matz  |  STEM/Robotics Educator*
Parallax Inc.  |  Direct: 916-625-3019  |  www.parallax.com  |  @M
atzElectronics <http://twitter.com/MatzElectronics>

**Comment by michel-cf** [comment]
I believe that the description stopped being required ever since I changed it to a rich text editor.

**Comment by wstodghill** [comment]
@michel-cf - you are correct sir! - A description is not required (at present).
@MatzElectronics - the titles make sense when you move on to the next window (also titled and you have a choice of moving back and forth via previous). This could help reduce the window size though.

**Comment by zfi** [comment]
Verified that the description block height has been reduced as requested. Closing this issue.
