### ISSUE TITLE
Date-stamp and/or version stamp projects at creation or update?

### ISSUE THREAD

**Issue by Steph-Parallax** [parallaxinc/BlocklyProp#805]
Suggest adding a date stamp, or a Blockly version stamp, to projects (visible where they are named and described.) 

Chris Savage observed some community projects behaving very oddly recently. Blocks were not visible, just a bit of debris in the top left corner.  He was not aware of the BlocklyProp update, and so did not know to refresh his browser aggressively. He tried to see when a particular community project was made, to see if it was from before the update or after, and realized there is no date or version information added when a project is created or saved.

**Comment by wstodghill** [comment]
@Steph-Parallax - Can you say more about this? I have had this problem before when there was an update, but I recently lost a couple of pieces of very complex code and not sure why either. I can probably recreate it, but it is frustrating. What do you mean by refreshing the browser aggressively?

![junk](https://cloud.githubusercontent.com/assets/8891440/19954280/f45c3236-a144-11e6-935d-a5dcb894b86a.JPG)

**Comment by zfi** [comment]
@wstodghill, the BlocklyProp code is JavaScript running on your browser. When we update the code on the server, those changes do not always propagate to your browser right away because of how browsers cache JavaScript files. The browser is given a list of JavaScript files to load but the browser may not load any or all of them if the file name of each file is the same in the pre and post update versions of the code. That mismatch can create havoc because the JavaScript files are no longer a matched set. The only way to correct that at the moment is to either use a private browsing session - which does not retain any knowledge of the JavaScript files, or flush the browser cache to ensure the browser no longer has the old version of the JavaScript files in the local cache.

With reference to your disappearing blocks, can you open an new issue that describes which blocks went missing? I have seen this happen before but was unable to identify to source.

**Comment by wstodghill** [comment]
@zfi - I will, but looking at the photo I posted above, if I right-click the gibberish in the upper left corner of the workspace, it shows that 55 blocks could be deleted. Without re-writing the program, I can try to remember which blocks, but the answer is that **all** are missing. 

I have deleted everything I can think of in memory and cache. I have run the program incognito and still nothing - I will try a different browser now - same results - just the little pile of junk in the upper left hand corner.

The last time this happened to me was following and update.

**Comment by Steph-Parallax** [comment]
Whit, when you see the small pile of gibberish, try clicking over to view
the code, then clicking back to see the blocks. Chris did this recently,
 and he was able to see most of the blocks though some of them were blacked
out.

Stephanie Lindsay
Product & Docs Manager
Parallax Inc.

916-625-3077
www.parallax.com
learn.parallax.com

**Comment by wstodghill** [comment]
@Steph-Parallax  Thanks Stephanie! See attached for code in question. 

@zfi - still want me to open a new issue?
[BlocklyProp1350.1.pdf](https://github.com/parallaxinc/BlocklyProp/files/570561/BlocklyProp1350.1.pdf)
[BlocklyProp1350.2.pdf](https://github.com/parallaxinc/BlocklyProp/files/570562/BlocklyProp1350.2.pdf)

**Comment by MatzElectronics** [comment]
@wstodghill we are figuring this out - and I'll create a separate issue for it.  Date created and Date Last Modified are available in the project database, and I think they could be listed on the project info page when you click into your project.  That would allow users to help support figure out why their project has broken, which would then allow us to diagnose and repair it.

Edits to the database the would prevent a lot of this in the first place, and possible bring back some projects that were broken in older updates is it's own issue, and I'll add that next.
Thanks!

**Comment by MatzElectronics** [comment]
Tested and verified.
