### ISSUE TITLE
Add robot blocks

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#816]
Add robot blocks to Propeller Activity Board WX profile

**Comment by MatzElectronics** [comment]
Tested, failed, will submit an update

**Comment by mrodriguez-parallax** [comment]
Robots blocks test results.



The Display calibration block cannot display readable data. Data scrolls horizontally and is hard to read.
![image](https://cloud.githubusercontent.com/assets/20686764/20815077/43543292-b7d1-11e6-8c1a-39990c482422.png)

![image](https://cloud.githubusercontent.com/assets/20686764/20815769/1a35bcf2-b7d4-11e6-83b9-3d8e77f914ce.png)



Activity Bot Calibration seems to go well but cannot verify since displayed data is unreadable
![image](https://cloud.githubusercontent.com/assets/20686764/20814911/809bc558-b7d0-11e6-86e0-d204e61473d7.png)


The Activity Bot block performed as expected. The block ramped the Activity bot to speeds of 64 and 128 using various ramping speeds like light, medium, heavy, and ,maximum. No obvious issues observed.
![image](https://cloud.githubusercontent.com/assets/20686764/20815296/23f62260-b7d2-11e6-8df2-e55e3c9ea1e6.png)



The Arlo robot block works okay when there's no ramping involved, however once ramping of any kind is introduced (light, medium, heavy, maximum) the Arlo does not move in any direction.
![image](https://cloud.githubusercontent.com/assets/20686764/20814693/9f12f494-b7cf-11e6-9ede-83a0ed47eaac.png)



The servo differential drive block was able to drive each wheel independently in either direction however no ramping was observed. I tried moving each wheel independently at the same time while trying to introduce ramping. Both wheels observed the same speeds at all ramping levels thus no ramping was observed.
![image](https://cloud.githubusercontent.com/assets/20686764/20816003/15d448bc-b7d5-11e6-84da-9af04ff4e665.png)




The Drive Stop block worked as expected.
![image](https://cloud.githubusercontent.com/assets/20686764/20815362/66b93ed4-b7d2-11e6-9c9f-9ef561116d22.png)

**Comment by MatzElectronics** [comment]
@mrodriguez-parallax can you pull the generated code for Arlo into SimpleIDE and see what you have to do to get it to work?  I'm not sure what's causing the problem - and we may need @AndyLindsay to take a look at it - the units for ramping might be different for Arlo.

If you can, try to do the same for the diff drive - what code changes need to be made to get it to start ramping?

Once we know that, I can make the changes accordingly in the block generators.
Thanks!

**Comment by MatzElectronics** [comment]
Still have an error on the display calibration interpolation table - everything else is tested and verified.

**Comment by MatzElectronics** [comment]
Only remaining problem is described in another issue.  Closing.
