### ISSUE TITLE
Database cleanup and old project "unbreaking"

### ISSUE THREAD

**Issue by MatzElectronics** [parallaxinc/BlocklyProp#843]
@kgracey @PropGit @zfi and I appear to be able to salvage some projects that were previously broken with block changes were made.  In the process, we've discovered a few other things that may be worth discussing.

There are a lot of "empty" projects - someone opens a new project, plays a bit, and leaves without saving anything.  **I propose a cron that finds empty projects that are three or more weeks old and deletes them.**  Thoughts?

Some projects may not be worth salvaging - I know why they are broken, but putting a repair that brings them back to life is labor intensive - so I'd like to know where the line is - if it's been dead since Mid-October, can we just stick a fork in it and call it done?  **I propose deleting projects with known deprecated blocks that are causing breakage that have been broken for over 2 months.**

Some block changes didn't completely destroy projects, but did alter them in a way that users can just select working menu options and/or add/replace value blocks.  I will try to fix these, but it may still require users to go in and make a few fixes.  **I propose informing users that they may need to make these changes to make their programs work again after an update.**

Whatever we decide to do, I think it's fair to give users a warning that we are messing with their projects, even if they are empty.  We can also offer to salvage them - it's potentially easier to save a few oldies than to try and come up with the large set of replace and regex functions it would require to fix them all.  **I propose informing users of the above and offering to repair upon request for older projects.**

**Comment by PropGit** [comment]
Truly empty projects (no blocks) seem to have no reason to remain in the database.  __An automated system that finds and removes those after a time period, whatever that may be, is a good thing.__

_...Automatically deleting projects with known deprecated blocks..._ Can we consider an opt-out or some way to preserve some projects regardless?  I've created a number of projects that are specifically intended to test certain features of things like the terminal.  They are named (and sometimes described) to relate directly to a specific GitHub issue and they explore edge cases, problem areas, and also successful functionality.  Just like going back in GitHub Issue history, those projects are an important tool for sanity checks and enhancements in the future.  I've experienced the deprecated block issue with these a number of times, but often in an instant I can see the problem and fix it.  Recreating the original from scratch with no reference but a faint memory is a lot more time consuming and in some cases, may be impossible because of lost mindset.  I think all these I'm talking about are marked private as they are not deemed important to share.  **Maybe there should be an ignore private projects exception, or something similar?**

_...informing users that they may need to make these changes to make their programs work again after an update_ __That shoulds great, but I don't know how we can administer that in a way that doesn't require extra human work.__

_I think it's fair to give users a warning that we are messing with their projects, even if they are empty._ __Agreed.__

**Comment by MatzElectronics** [comment]
After discussing with zfi - implementing a set of conditional string replacements against the code in the DAO Impl file.  This will correct user code on the fly as it's read out of the data base, and when the user saves it, it should get stored correctly.  That way it is easy to turn off and on and doesn't require us to monkey with the database.

**Comment by zfi** [comment]
No issues identified in testing. Closing the issue.
