### ISSUE TITLE
Comments on a "new processor" block 

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/BlocklyProp#870]
![image](https://cloud.githubusercontent.com/assets/9534148/21756550/6ac8a08c-d5d7-11e6-9168-a0c522a41011.png)
Comments are not properly formatted when placed in a new processor block. When comment is removed program can be compiled. 
```
   cog_run( // test comment  M2125_Accelerometer
        , 128);

```
http://blockly.parallax.com/blockly/editor/blocklyc.jsp?project=2677# in case you want to try it out.

**Comment by zfi** [comment]
Let's test this on the Demo site to verify that it is broken there.

**Comment by MatzElectronics** [comment]
It will be.  I'm not sure this can actually be fixed.  I'll do some
research, but I think we documented that the ONLY the run function block
can be used inside the new processor block.  I'll try to figure out how to
limit it to make sure it doesn't allow it or ignores other blocks.

**Comment by JonMcPhalen** [comment]
IMO, the new **processor block** should contain a single block that is a call to a function that runs in its own processor. The reason is that this block compiles to the cog_run() command which means anything other than a call to a function creates a mess in the code. 

Here's an example -- this structure always works.

![image](https://user-images.githubusercontent.com/4042568/27255991-84eec04a-535e-11e7-932f-34405816a3e3.png)

**Comment by JonMcPhalen** [comment]
Well, nevermind -- I see that Matt pointed out what I learned the hard way. Sorry.

**Comment by MatzElectronics** [comment]
Yes, but there is still room for improvement here.  The new processor block
could throw a warning if it detects anything other than a run function
block inside of it.  There are a number of these types of improvements that
could be made, so if you see them, keep pointing them out.

**Comment by JonMcPhalen** [comment]
The **repeat** blocks create proper for() loop structures... could the **new processor** block create a custom function to contain the cog_run and user blocks?
```
void np_001()
{
  cog_run(...)
  // user blocks here
}
```

**Comment by MatzElectronics** [comment]
Possibly...never thought to do that :)

On Jun 17, 2017 1:25 PM, "Jon McPhalen" <notifications@github.com> wrote:

The *repeat* blocks create proper for() loop structures... could the *new
processor* block create a custom function to contain the cog_run and user
blocks?

void np_001()
{
  cog_run(...)
  // user blocks here
}

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/parallaxinc/BlocklyProp/issues/870#issuecomment-309238166>,
or mute the thread

**Comment by JonMcPhalen** [comment]
The cog_run() needs to be in the mainline code, the user function added like any other. It might be useful to allow the **new processor** block to include a name set by the user. This will make the generated code more readable.

**Comment by MatzElectronics** [comment]
@JonMcPhalen I really like you idea...but I think we've painted ourselves into a bit of a corner.  The current method for using this block does work, and so I'm making a call not to change it.  What I have done is prevent anything other than a function block from being connected to it.  I am for the time being going to leave this open, because I still want to try to make the function call block mutate and "flatten" out it's bottom connector when it detects that it's inside of the new processor block.  It shouldn't be too difficult, I just need to work through it.

Thanks!

**Comment by MatzElectronics** [comment]
I'll update the labels once I get my recent changes loaded into demo.

**Comment by CarsonGracey** [comment]
Tested and Verified.
