### ISSUE TITLE
S3 constrain play note and play tone blocks

### ISSUE THREAD

**Issue by Steph-Parallax** [parallaxinc/BlocklyProp#914]
@dcarrier-parallax @MatzElectronics 

Issue: Reduce volume and restrict frequency of S3 sounds to a range that is practical with the speaker hardware.  (S3 is not primarily a musical instrument!)

**Play tone block**
volume: Cap at 50%. Block says "at a volume of 0 to 100%" now.  I don't think 50% would look good on the block, so this hopefully can be scaled in the library/object itself, and we can leave the block as-is.
frequency: cap at 2000 Hz

**Play note block**
**volume**: the options are quiet, medium, and loud. Cap at 50% of max possible. Hopefully that can be scaled in the library/object.  If notes are not audible at "quiet" then I would suggest just two options of "soft" and "loud" or something like that.
**frequency**: The drop-down menu seems to indicate octaves from pedal to double-high. The options need to be restricted to wherever 2000 Hz is not exceeded. I expect that "deep" and "pedal" may not be so audible at reduced volumes, so we may need to remove options from the lower end as well.

**Comment by MatzElectronics** [comment]
This is similar to #879 .  I'm on it!

**Comment by MatzElectronics** [comment]
Halved speaker volume, removed highest and lowest octaves, and changed labeling to suggest limit of 2kHz on play tones block. (You can still enter a higher value - this will need to be clamped in the library, not on the generated code)  Ready for testing.

**Comment by MatzElectronics** [comment]
Here is from #879 (Combining because of the similar nature of the issues):

Update C blocks that target the Scribbler to cap volume at 50% and frequency around 1000 Hz. Changes to underlying resources for handling music generation planned.

(Currently Blockly setting can go to 10 kHz. If keeping this desired for physics games, I suggest a separate C (not Scribbler-specific) block that also brings out the option for sine, square, and sawtooth waves in a drop-down.)

**Comment by MatzElectronics** [comment]
These blocks need to be tested in BOTH SPIN and C.

**Comment by MatzElectronics** [comment]
Verified in C, closing because the system is switching soon.
